# Generated by Django 2.2.19 on 2021-03-08 15:45

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_formfield_clean_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='help text'),
        ),
    ]
