# Generated by Django 2.2.12 on 2021-03-25 00:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_make_intro_rich_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpage",
            name="key_details",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
