# Generated by Django 2.2.12 on 2020-06-03 10:02

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaOfExpertise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="StaffPageAreOfExpertisePlacement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_of_expertise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_staff",
                        to="people.AreaOfExpertise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffPagePageRelatedProjects",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="StaffPageRelatedResearchPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="StaffPageRelatedSchoolPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.RemoveField(model_name="staffpagephonenumber", name="page"),
        migrations.RenameField(
            model_name="staffpage", old_name="image", new_name="profile_image"
        ),
        migrations.RemoveField(model_name="staffpage", name="website"),
        migrations.AddField(
            model_name="staffpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [
                    (
                        "slide",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("link", wagtail.blocks.URLBlock(required=False)),
                                (
                                    "course",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Gallery",
            ),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="more_information",
            field=wagtail.fields.StreamField(
                [
                    (
                        "accordion_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="A large heading diplayed next to the block",
                                        required=False,
                                    ),
                                ),
                                (
                                    "preview_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="The text to display when the accordion is collapsed",
                                        required=False,
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "h2",
                                            "h3",
                                            "bold",
                                            "italic",
                                            "image",
                                            "ul",
                                            "ol",
                                            "link",
                                        ],
                                        help_text="The content shown when the accordion expanded",
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="An optional link to display below the expanded content",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="More information",
            ),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="more_information_title",
            field=models.CharField(default="More information", max_length=80),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="related_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("url", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Related Links",
            ),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="research_highlights_title",
            field=models.CharField(
                blank=True,
                help_text="The title value displayed above the Research highlights gallery showing project pages",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="staffpage",
            name="staff_title",
            field=models.CharField(
                blank=True, help_text="E.G Dr, Professor", max_length=255
            ),
        ),
        migrations.DeleteModel(name="SocialMediaProfile"),
        migrations.DeleteModel(name="StaffPagePhoneNumber"),
        migrations.AddField(
            model_name="staffpagerelatedschoolpage",
            name="source_page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_school_pages",
                to="people.StaffPage",
            ),
        ),
        migrations.AddField(
            model_name="staffpagerelatedresearchpage",
            name="source_page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_research_centre_pages",
                to="people.StaffPage",
            ),
        ),
        migrations.AddField(
            model_name="staffpagepagerelatedprojects",
            name="source_page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_projects",
                to="people.StaffPage",
            ),
        ),
        migrations.AddField(
            model_name="staffpageareofexpertiseplacement",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_area_of_expertise",
                to="people.StaffPage",
            ),
        ),
    ]
