# Generated by Django 2.2.12 on 2020-06-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_improve_relationships_between_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpage",
            name="legacy_staff_id",
            field=models.IntegerField(
                blank=True,
                help_text="Add the legacy staff page ID here to show related students",
                null=True,
            ),
        ),
    ]
