# Generated by Django 2.2.12 on 2020-06-08 09:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_staffpage_legacy_staff_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPageManualRelatedStudents",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("link", models.URLField(blank=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_students_manual",
                        to="people.StaffPage",
                    ),
                ),
            ],
        ),
    ]
