# Generated by Django 2.2.12 on 2020-06-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_staffindexpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffpageareofexpertiseplacement",
            name="area_of_expertise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_staff",
                to="people.AreaOfExpertise",
                verbose_name="Areas of expertise",
            ),
        ),
    ]
