# Generated by Django 2.2.12 on 2020-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_staffindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="areaofexpertise",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
