# Generated by Django 2.2.12 on 2020-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0009_update_expertise_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffpage",
            name="legacy_staff_id",
            field=models.IntegerField(
                blank=True,
                help_text="Add the legacy staff page ID here to show related students. This can be found by editing the page on the legacy site and copying the number from the URL, E.G, /admin/pages/3365/edit",
                null=True,
            ),
        ),
    ]
