# Generated by Django 2.2.12 on 2020-06-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0009_areaofexpertise_slug"),
        ("people", "0010_improve_help_text"),
    ]

    operations = []
