# Generated by Django 2.2.12 on 2020-07-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_merge_20200618_1656'),
        ('people', '0011_merge_20200622_1033'),
    ]

    operations = [
    ]
