# Generated by Django 2.2.12 on 2020-09-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_directorate_staffpagedirectorate"),
        ("people", "0012_merge_20200713_1249"),
    ]

    operations = []
