# Generated by Django 2.2.12 on 2021-02-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_directorate_staffpagedirectorate"),
        ("people", "0013_make_social_links_not_required"),
    ]

    operations = []
