# Generated by Django 2.2.12 on 2021-02-18 08:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0018_name_updates"),
        ("people", "0016_add_information_field_and_related_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="DegreeStatus",
            fields=[
                (
                    "sluggedtaxonomy_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="utils.SluggedTaxonomy",
                    ),
                ),
            ],
            bases=("utils.sluggedtaxonomy",),
        ),
        migrations.CreateModel(
            name="DegreeType",
            fields=[
                (
                    "sluggedtaxonomy_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="utils.SluggedTaxonomy",
                    ),
                ),
            ],
            bases=("utils.sluggedtaxonomy",),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="degree_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="degree_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="bio",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Add a detail summary", verbose_name="Abstract"
            ),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="introduction",
            field=models.TextField(blank=True, verbose_name="Project title"),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="degree_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_student",
                to="people.DegreeStatus",
            ),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="degree_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_student",
                to="people.DegreeType",
            ),
        ),
    ]
