# Generated by Django 2.2.12 on 2021-03-10 08:37

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_extends_image_fields"),
        ("people", "0017_field_additions_for_filters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentpage",
            name="gallery",
        ),
        migrations.RemoveField(
            model_name="studentpage",
            name="more_information",
        ),
        migrations.RemoveField(
            model_name="studentpage",
            name="more_information_title",
        ),
        migrations.RemoveField(
            model_name="studentpage",
            name="related_links",
        ),
        migrations.RemoveField(
            model_name="studentpage",
            name="social_links",
        ),
        migrations.AddField(
            model_name="studentpage",
            name="addition_information_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="additional_information_title",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="awards",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="conferences",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="degrees",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="exhibitions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="experience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="funding",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="publications",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="research_outputs",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="StudentPageSocialLinks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "link_title",
                    models.CharField(
                        help_text="The text displayed for the link", max_length=120
                    ),
                ),
                ("url", models.URLField()),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_links",
                        to="people.StudentPage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentPageRelatedLinks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "link_title",
                    models.CharField(
                        help_text="The text displayed for the link", max_length=120
                    ),
                ),
                ("url", models.URLField()),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatedlinks",
                        to="people.StudentPage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentPageGallerySlide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=120)),
                ("author", models.CharField(max_length=120)),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_slides",
                        to="people.StudentPage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
