# Generated by Django 2.2.12 on 2021-03-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0017_field_additions_for_filters"),
    ]

    operations = [
        migrations.RemoveField(model_name="studentpage", name="more_information",),
        migrations.RemoveField(
            model_name="studentpage", name="more_information_title",
        ),
        migrations.AddField(
            model_name="studentpage",
            name="addition_information_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="additional_information_title",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage", name="awards", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="conferences",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="degrees",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="exhibitions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="experience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="funding",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="publications",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="research_outputs",
            field=models.TextField(blank=True),
        ),
    ]
