# Generated by Django 2.2.12 on 2021-03-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0018_replace_streamfields_for_explicit_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentpage",
            name="research_highlights_title",
        ),
    ]
