# Generated by Django 2.2.12 on 2021-03-16 12:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0019_remove_studentpage_research_highlights_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentpage",
            name="addition_information_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="awards",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="biography",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="conferences",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="degrees",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="exhibitions",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="experience",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="funding",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="publications",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentpage",
            name="research_outputs",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
