# Generated by Django 2.2.12 on 2021-03-24 22:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0021_remove_student_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpage",
            name="link_to_final_thesis",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="studentpage",
            name="student_funding",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name="StudentPageSupervisor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="E.G, Dr, Mrs, etc", max_length=20
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("surname", models.CharField(blank=True, max_length=255)),
                ("link", models.URLField(blank=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_supervisor",
                        to="people.StudentPage",
                    ),
                ),
                (
                    "supervisor_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="people.StaffPage",
                    ),
                ),
            ],
        ),
    ]
