# Generated by Django 2.2.19 on 2021-04-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0022_adds_supervisor_and_funding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentpage",
            name="degree_type",
        ),
    ]
