# Generated by Django 2.2.19 on 2021-04-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0023_remove_degree_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpage",
            name="degree_award",
            field=models.CharField(
                blank=True, choices=[("1", "MPhil"), ("2", "PhD")], max_length=1
            ),
        ),
    ]
