# Generated by Django 3.1.7 on 2021-04-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0024_studentpage_degree_award"),
        ("people", "0013_merge_20200915_1649"),
    ]

    operations = []
