# Generated by Django 3.1.7 on 2021-04-21 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import rca.people.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0024_studentpage_student_user_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentpage",
            name="student_user_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=rca.people.models.StudentPage.get_student_users,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
