# Generated by Django 3.1.7 on 2021-04-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0024_studentpage_degree_award"),
        ("people", "0025_limit_student_choices"),
    ]

    operations = []
