# Generated by Django 3.1.7 on 2021-04-28 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0026_merge_20210423_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentpage",
            name="student_user_account",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"groups__name": "Students"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
