# Generated by Django 3.1.7 on 2021-04-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("people", "0027_switch_to_one_to_one_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpage",
            name="student_user_image_collection",
            field=models.OneToOneField(
                blank=True,
                help_text="This should link to this students image collection",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtailcore.collection",
            ),
        ),
    ]
