# Generated by Django 3.1.7 on 2021-05-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0028_studentpage_student_user_image_collection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentpage", name="student_user_image_collection",
        ),
    ]
