# Generated by Django 3.1.10 on 2021-08-25 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0028_studentpage_student_user_image_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpagemanualrelatedstudents",
            name="student_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_programme",
                to="people.studentpage",
            ),
        ),
        migrations.AlterField(
            model_name="staffpagemanualrelatedstudents",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="staffpagemanualrelatedstudents",
            name="status",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="staffpagemanualrelatedstudents",
            name="surname",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
