# Generated by Django 4.2.17 on 2025-04-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0034_required_title_and_play_button_label_gallery_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpage",
            name="research_profile_url",
            field=models.URLField(blank=True),
        ),
    ]
