# Generated by Django 2.2.4 on 2019-08-13 08:29

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_customdocument_file_hash"),
        ("images", "0002_customimage_file_hash"),
        ("programmes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DegreeLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=128)),
                ("slug", models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(model_name="programmepage", name="body"),
        migrations.RemoveField(model_name="programmepage", name="introduction"),
        migrations.AddField(
            model_name="programmepage",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="application_deadline_options",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Applications closed. Please check back soon."),
                    ("2", "Still accepting applications"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="hero_colour_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Light text on a dark image"),
                    ("2", "Dark text on a light image"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="hero_video",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="hero_video_preview_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="link_to_open_days",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="next_open_day_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_details_credits",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_details_credits_suffix",
            field=models.CharField(
                blank=True,
                choices=[("1", "credits"), ("2", "credits at FHEQ Level 6")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_details_duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Full-time study"),
                    ("2", "Full-time study with part-time option"),
                    ("3", "Part-time study"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_details_time",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_details_time_suffix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "year programme"),
                    ("2", "month programme"),
                    ("3", "week programme"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.CustomDocument",
            ),
        ),
        migrations.CreateModel(
            name="ProgrammePageProgrammeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programme_types",
                        to="programmes.ProgrammePage",
                    ),
                ),
                (
                    "programme_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programmes.ProgrammeType",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammePageCareerOpportunities",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_opportunities",
                        to="programmes.ProgrammePage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.AddField(
            model_name="programmepage",
            name="degree_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="programmes.DegreeLevel",
            ),
        ),
    ]
