# Generated by Django 2.2.4 on 2019-08-15 06:25

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_customimage_file_hash"),
        ("programmes", "0002_fields_for_overview_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="contact_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="contact_link_text",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="contact_link_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="contact_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="contact_title",
            field=models.CharField(default="Contact us", max_length=125),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="facilities_copy",
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="facilities_gallery",
            field=wagtail.fields.StreamField(
                [
                    (
                        "slide",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="facilities_intro",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="facilities_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="facilities_link_text",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="notable_alumni_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Link_to_person",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock()),
                                ("link", wagtail.blocks.URLBlock()),
                            ],
                            icon="link",
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="notable_alumni_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_description_copy",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_description_subtitle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_description_title",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_gallery",
            field=wagtail.fields.StreamField(
                [
                    (
                        "slide",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("link", wagtail.blocks.URLBlock(required=False)),
                                (
                                    "course",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Programme gallery",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_gallery_title",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="related_content_title",
            field=models.CharField(
                blank=True,
                help_text="Large title displayed above the related content items, EG 'More opportunities to study at the RCA'",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="application_deadline_options",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Applications closed. Please check back soon."),
                    ("2", "Still accepting applications"),
                ],
                default="",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="hero_colour_option",
            field=models.CharField(
                choices=[
                    ("1", "Light text on a dark image"),
                    ("2", "Dark text on a light image"),
                ],
                default="",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="hero_video",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="link_to_open_days",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="programme_details_credits",
            field=models.CharField(blank=True, default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="programme_details_credits_suffix",
            field=models.CharField(
                blank=True,
                choices=[("1", "credits"), ("2", "credits at FHEQ Level 6")],
                default="",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="programme_details_duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Full-time study"),
                    ("2", "Full-time study with part-time option"),
                    ("3", "Part-time study"),
                ],
                default="",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="programme_details_time",
            field=models.CharField(blank=True, default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="programme_details_time_suffix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "year programme"),
                    ("2", "month programme"),
                    ("3", "week programme"),
                ],
                default="",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programmepagerelatedprogramme",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
    ]
