# Generated by Django 2.2.4 on 2019-08-19 12:19

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0003_remaining_overview_section_fields")]

    operations = [
        migrations.AlterField(
            model_name="programmepage",
            name="notable_alumni_links",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "Link_to_person",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("name", wagtail.core.blocks.CharBlock()),
                                ("link", wagtail.core.blocks.URLBlock(required=False)),
                            ],
                            icon="link",
                        ),
                    )
                ],
                blank=True,
            ),
        )
    ]
