# Generated by Django 2.2.4 on 2019-08-20 15:17

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0006_add_requirements_section_fields")]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="more_information_blocks",
            field=wagtail.fields.StreamField(
                [
                    (
                        "information_block",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("text", wagtail.blocks.RichTextBlock()),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="scholarship_accordion_items",
            field=wagtail.fields.StreamField(
                [
                    (
                        "accodrion",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="A large heading diplayed next to the block",
                                        required=False,
                                    ),
                                ),
                                (
                                    "preview_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="The text to display when the accordion is collapsed",
                                        required=False,
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "h2",
                                            "h3",
                                            "bold",
                                            "italic",
                                            "image",
                                        ],
                                        help_text="The content shown when the accordion expanded",
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="An optional link to display below the expanded content",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="scholarship_information_blocks",
            field=wagtail.fields.StreamField(
                [
                    (
                        "information_block",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("text", wagtail.blocks.RichTextBlock()),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="scholarships_information",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="programmepage",
            name="scholarships_title",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProgrammePageFeeItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title for the information, e.g 'Fees for new students ",
                        max_length=120,
                    ),
                ),
                (
                    "introduction",
                    models.CharField(
                        help_text="Extra information about the fee items",
                        max_length=250,
                    ),
                ),
                (
                    "row",
                    wagtail.fields.StreamField(
                        [
                            (
                                "row",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "location",
                                            wagtail.blocks.CharBlock(
                                                help_text="e.g. Home and EU",
                                                max_length=120,
                                            ),
                                        ),
                                        (
                                            "subsidised",
                                            wagtail.blocks.BooleanBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "per_year_cost",
                                            wagtail.blocks.CharBlock(
                                                help_text="e.g. £14,200 per year",
                                                max_length=120,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "total_cost",
                                            wagtail.blocks.CharBlock(
                                                help_text="e.g. £28,400 total fee",
                                                max_length=120,
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_items",
                        to="programmes.ProgrammePage",
                    ),
                ),
            ],
        ),
    ]
