# Generated by Django 2.2.4 on 2019-08-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0009_add_related_staff_fields")]

    operations = [
        migrations.AlterField(
            model_name="programmepage",
            name="hero_colour_option",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Light text on a dark image"),
                    (2, "Dark text on a light image"),
                ]
            ),
        )
    ]
