# Generated by Django 2.2.4 on 2019-08-23 11:00

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0010_use_ingeger_for_hero_option")]

    operations = [
        migrations.AlterField(
            model_name="programmepagefeeitem",
            name="row",
            field=wagtail.fields.StreamField(
                [
                    (
                        "row",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "location",
                                    wagtail.blocks.CharBlock(
                                        help_text="E.g. Home and EU", max_length=120
                                    ),
                                ),
                                (
                                    "subsidised",
                                    wagtail.blocks.BooleanBlock(required=False),
                                ),
                                (
                                    "per_year_cost",
                                    wagtail.blocks.CharBlock(
                                        help_text="E.g. £14,200 per year",
                                        max_length=120,
                                        required=False,
                                    ),
                                ),
                                (
                                    "total_cost",
                                    wagtail.blocks.CharBlock(
                                        help_text="E.g. £28,400 total fee",
                                        max_length=120,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        )
    ]
