# Generated by Django 2.2.4 on 2019-08-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0011_make_fees_row_optional")]

    operations = [
        migrations.RemoveField(model_name="programmepage", name="hero_colour_option")
    ]
