# Generated by Django 2.2.4 on 2019-08-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0014_make_fees_orderable")]

    operations = [
        migrations.RemoveField(model_name="programmepage", name="contact_link_text"),
        migrations.RemoveField(model_name="programmepage", name="contact_link_url"),
        migrations.RemoveField(model_name="programmepage", name="contact_text"),
        migrations.RemoveField(model_name="programmepage", name="contact_title"),
        migrations.RemoveField(model_name="programmepage", name="notable_alumni_text"),
        migrations.RemoveField(model_name="programmepage", name="pathways_information"),
        migrations.RemoveField(
            model_name="programmepage", name="related_content_title"
        ),
        migrations.RemoveField(
            model_name="programmepage", name="requirements_subtitle"
        ),
        migrations.RemoveField(model_name="programmepage", name="requirements_text"),
    ]
