# Generated by Django 2.2.4 on 2019-09-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0015_remove_unwanted_fields")]

    operations = [
        migrations.AlterField(
            model_name="programmepage",
            name="facilities_copy",
            field=models.TextField(
                blank=True, help_text="Max length 400 characters", max_length=400
            ),
        )
    ]
