# Generated by Django 2.2.4 on 2019-09-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0016_add_facilities_copy_help_text")]

    operations = [
        migrations.AlterField(
            model_name="programmepagefeeitem",
            name="introduction",
            field=models.CharField(
                blank=True,
                help_text="Extra information about the fee items",
                max_length=250,
            ),
        )
    ]
