# Generated by Django 2.2.4 on 2019-09-05 15:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0021_allow_ul_ol_for_accordion")]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="requirements_text",
            field=wagtail.fields.RichTextField(blank=True),
        )
    ]
