# Generated by Django 2.2.4 on 2019-09-06 10:21

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0024_add_accordion_snippet")]

    operations = [
        migrations.AlterField(
            model_name="programmepage",
            name="steps",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "step",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("heading", wagtail.core.blocks.CharBlock()),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.core.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.core.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "step_snippet",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            "utils.StepSnippet"
                        ),
                    ),
                ],
                blank=True,
            ),
        )
    ]
