# Generated by Django 2.2.4 on 2019-09-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0007_add_fee_disclaimer_snippet"),
        ("programmes", "0025_add_step_snippets"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="fees_disclaimer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utils.FeeDisclaimerSnippet",
            ),
        )
    ]
