# Generated by Django 2.2.4 on 2019-09-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0027_add_accordion_snippet_to_requirements_field")]

    operations = [
        migrations.RemoveField(
            model_name="programmepage", name="programme_gallery_title"
        )
    ]
