# Generated by Django 2.2.4 on 2019-09-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0029_remove_staff_link_title")]

    operations = [
        migrations.RemoveField(model_name="programmepage", name="facilities_link"),
        migrations.RemoveField(model_name="programmepage", name="facilities_link_text"),
    ]
