# Generated by Django 2.2.4 on 2019-09-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0030_movel_link_to_snippet")]

    operations = [
        migrations.RemoveField(model_name="programmepage", name="pathways_summary")
    ]
