# Generated by Django 2.2.4 on 2019-09-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0031_remove_pathways_summary")]

    operations = [
        migrations.RemoveField(model_name="programmepage", name="apply_cta_link"),
        migrations.RemoveField(model_name="programmepage", name="apply_cta_text"),
        migrations.RemoveField(
            model_name="programmepage", name="apply_image_sub_title"
        ),
        migrations.RemoveField(model_name="programmepage", name="apply_image_title"),
        migrations.RemoveField(model_name="programmepage", name="apply_title"),
    ]
