# Generated by Django 2.2.4 on 2019-09-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0034_alter_accordion_and_info_blocks")]

    operations = [
        migrations.AlterField(
            model_name="programmepage",
            name="programme_description_subtitle",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="programme_description_title",
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
