# Generated by Django 2.2.4 on 2019-09-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0036_add_apply_tab_control")]

    operations = [
        migrations.AlterField(
            model_name="programmepage",
            name="disable_apply_tab",
            field=models.BooleanField(
                default=0,
                help_text="This setting will remove the apply tab from this programme. This setting is ignored if the feature has already been disabled at the global level in Settings > Programme settings.",
            ),
        )
    ]
