# Generated by Django 2.2.4 on 2019-09-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_customimage_file_hash"),
        ("programmes", "0037_update_help_texts"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="programme_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_video",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="programme_video_caption",
            field=models.CharField(
                blank=True,
                help_text="The text dipsplayed next to the video play button",
                max_length=80,
            ),
        ),
    ]
