# Generated by Django 2.2.9 on 2020-01-30 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("programmes", "0038_add_overview_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammePageGlobalFieldsSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_content_title",
                    models.CharField(
                        default="More opportunities to study at the RCA", max_length=255
                    ),
                ),
                (
                    "related_content_subtitle",
                    models.CharField(default="Related programmes", max_length=255),
                ),
                (
                    "key_details_next_open_day_title",
                    models.CharField(
                        default="Next open day",
                        max_length=255,
                        verbose_name="Next open days title",
                    ),
                ),
                (
                    "key_details_book_or_view_all_open_days_link_title",
                    models.CharField(
                        default="Book or view all open days",
                        max_length=255,
                        verbose_name="Book open days title",
                    ),
                ),
                (
                    "key_details_application_deadline_title",
                    models.CharField(
                        default="Application deadline",
                        max_length=255,
                        verbose_name="Application deadline title",
                    ),
                ),
                (
                    "key_details_career_opportunities_title",
                    models.CharField(
                        default="Career opportunities",
                        max_length=255,
                        verbose_name="Opportunities title",
                    ),
                ),
                (
                    "key_details_pathways_information_link_title",
                    models.CharField(
                        default="Visit the Curriculum tab for more information.",
                        max_length=255,
                        verbose_name="Pathways information link title",
                    ),
                ),
                (
                    "alumni_summary_text",
                    models.CharField(
                        default="Our alumni form an international network of creative individuals who have shaped and continue to shape the world.",
                        max_length=255,
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(default="Ask a question", max_length=255),
                ),
                (
                    "contact_text",
                    models.CharField(
                        default="Get in touch if you’d like to find out more or have any questions.",
                        max_length=255,
                    ),
                ),
                (
                    "pathways_summary",
                    models.CharField(
                        default="When applying for this programme, you select one of these specialist pathways.",
                        max_length=255,
                    ),
                ),
                (
                    "requirements_introduction",
                    models.CharField(
                        default="What you need to know before you apply", max_length=255
                    ),
                ),
                (
                    "scholarships_section_title",
                    models.CharField(default="Scholarships", max_length=255),
                ),
                (
                    "apply_title",
                    models.CharField(default="Start your application", max_length=255),
                ),
                (
                    "apply_image_title",
                    models.CharField(
                        default="Change your life and be here in 2020", max_length=255
                    ),
                ),
                (
                    "apply_image_sub_title",
                    models.CharField(
                        default="The royal college of art welcomes applicants from all over the world",
                        max_length=255,
                    ),
                ),
                (
                    "apply_cta_link",
                    models.CharField(
                        default="https://applications.rca.ac.uk/", max_length=255
                    ),
                ),
                (
                    "apply_cta_text",
                    models.CharField(
                        default="Visit our applications portal to get started",
                        max_length=255,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.Site",
                    ),
                ),
            ],
            options={"verbose_name": "Programme Page Global Fields"},
        )
    ]
