# Generated by Django 2.2.9 on 2020-01-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0039_programmepageglobalfieldssettings"),
        ("programmes", "0039_add_listing_fields"),
    ]

    operations = []
