# Generated by Django 2.2.9 on 2020-01-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("programmes", "0039_add_listing_fields")]

    operations = [
        migrations.RemoveField(model_name="programmetype", name="legacy_slug"),
        migrations.RemoveField(model_name="programmetype", name="slug"),
    ]
