# Generated by Django 2.2.9 on 2020-01-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0040_remove_fields_from_programme_type")]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=500)),
            ],
        )
    ]
