# Generated by Django 2.2.9 on 2020-01-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0042_programme_page_schools_page_relationship")]

    operations = [
        migrations.AddField(
            model_name="programmetype",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        )
    ]
