# Generated by Django 2.2.9 on 2020-01-13 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0044_adds_subject_taxonomy_relationship")]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="programme_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="programmes.ProgrammeType",
            ),
        ),
        migrations.DeleteModel(name="ProgrammePageProgrammeType"),
    ]
