# Generated by Django 2.2.9 on 2020-01-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0046_update_subject_to_support_multiple_values")]

    operations = [
        migrations.AlterField(
            model_name="programmepagesubjectplacement",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programmes",
                to="programmes.Subject",
            ),
        )
    ]
