# Generated by Django 2.2.9 on 2020-01-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0040_merge_20200113_1546"),
        ("programmes", "0047_update_related_name"),
    ]

    operations = []
