# Generated by Django 2.2.9 on 2020-01-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0047_update_related_name")]

    operations = [
        migrations.AddField(
            model_name="programmeindexpage",
            name="contact_text",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="programmeindexpage",
            name="contact_title",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
