# Generated by Django 2.2.9 on 2020-01-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0048_merge_20200116_1548"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmepageglobalfieldssettings",
            name="key_details_programme_details_title",
        ),
    ]
