# Generated by Django 2.2.9 on 2020-01-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0048_adds_contact_fields")]

    operations = [
        migrations.AlterModelOptions(
            name="programmetype", options={"ordering": ["sort_order"]}
        ),
        migrations.AddField(
            model_name="programmetype",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
