# Generated by Django 2.2.9 on 2020-01-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0049_make_programme_type_orderable"),
        (
            "programmes",
            "0049_remove_programmepageglobalfieldssettings_key_details_programme_details_title",
        ),
    ]

    operations = []
