# Generated by Django 2.2.9 on 2020-01-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0049_make_programme_type_orderable"),
        ("programmes", "0048_merge_20200116_1548"),
    ]

    operations = []
