# Generated by Django 2.2.9 on 2020-02-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0049_make_programme_type_orderable"),
        ("programmes", "0039_programmepageglobalfieldssettings"),
    ]

    operations = []
