# Generated by Django 2.2.9 on 2020-02-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0050_merge_20200131_1810"),
        ("programmes", "0050_merge_20200206_1206"),
    ]

    operations = []
