# Generated by Django 2.2.12 on 2020-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programmes", "0051_update_revisions")]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="hero_image_credit",
            field=models.CharField(
                blank=True,
                help_text="Adding specific credit text here will         override the images meta data fields.",
                max_length=255,
            ),
        )
    ]
