# Generated by Django 2.2.9 on 2020-03-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0051_update_revisions"),
        ("programmes", "0051_merge_20200207_1702"),
    ]

    operations = []
