# Generated by Django 2.2.12 on 2020-04-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0052_add_hero_image_credit"),
        ("programmes", "0052_redefine_schools_and_research_relationships"),
    ]

    operations = []
