# Generated by Django 2.2.12 on 2020-04-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0052_redefine_schools_and_research_relationships"),
        ("programmes", "0052_add_hero_image_credit"),
    ]

    operations = []
