# Generated by Django 2.2.12 on 2020-04-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0052_merge_20200312_1124"),
        ("programmes", "0052_redefine_schools_and_research_relationships"),
    ]

    operations = []
