# Generated by Django 2.2.12 on 2020-05-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0053_merge_20200430_0923"),
        ("programmes", "0054_merge_20200423_1628"),
    ]

    operations = []
