# Generated by Django 2.2.12 on 2020-08-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0055_merge_20200505_1521"),
        ("programmes", "0054_adds_staff_page_relationship"),
    ]

    operations = []
