# Generated by Django 2.2.12 on 2021-02-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0058_merge_20210210_0850"),
        ("programmes", "0056_merge_20200803_2053"),
    ]

    operations = []
