# Generated by Django 2.2.12 on 2021-03-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0058_merge_20210210_0850"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="qs_code",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="This code needs to match the name of the codeExternal value in QS, E.G 105",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programmetype",
            name="qs_code",
            field=models.CharField(
                blank=True,
                help_text="This code needs to match the name of the LevelOfStudy code value in QS",
                max_length=500,
            ),
        ),
    ]
