# Generated by Django 2.2.19 on 2021-04-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0058_merge_20210210_0850"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmepage",
            name="hero_colour_option",
        ),
    ]
