# Generated by Django 3.1.7 on 2021-04-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0059_add_qs_code"),
        ("programmes", "0059_remove_hero_colour_options"),
    ]

    operations = []
