# Generated by Django 2.2.12 on 2021-03-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0059_merge_20210212_1510"),
        ("programmes", "0059_add_qs_code"),
    ]

    operations = []
