# Generated by Django 2.2.19 on 2021-04-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0059_remove_hero_colour_options"),
        ("programmes", "0059_add_qs_code"),
    ]

    operations = []
