# Generated by Django 3.1.7 on 2021-04-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0060_merge_20210319_1014"),
        ("programmes", "0059_remove_hero_colour_options"),
    ]

    operations = []
