# Generated by Django 3.1.10 on 2021-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0060_add_contact_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
