# Generated by Django 3.1.7 on 2021-05-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0061_programmepage_mailchimp_group_name"),
        ("programmes", "0061_merge_20210428_1305"),
    ]

    operations = []
