# Generated by Django 3.1.10 on 2021-08-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0062_add_subject_slugs"),
        ("programmes", "0061_programmepage_mailchimp_group_name"),
    ]

    operations = []
