# Generated by Django 3.1.10 on 2021-08-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0063_add_tap_widget"),
        ("programmes", "0063_merge_20210802_1127"),
    ]

    operations = []
