# Generated by Django 3.1.10 on 2021-08-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0063_merge_20210802_1127"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmetype",
            name="qs_code",
        ),
    ]
