# Generated by Django 3.1.10 on 2021-09-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0063_add_tap_widget"),
        ("programmes", "0064_remove_qs_code"),
    ]

    operations = []
