# Generated by Django 3.1.10 on 2021-08-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0064_merge_20210802_1140"),
        ("programmes", "0064_remove_qs_code"),
    ]

    operations = []
