# Generated by Django 3.1.10 on 2021-09-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0065_merge_20210810_1049"),
        ("programmes", "0065_merge_20210910_1128"),
    ]

    operations = []
