# Generated by Django 3.1.10 on 2021-10-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0066_merge_20210927_1519"),
        ("programmes", "0066_add_intranet_slug_for_imports"),
    ]

    operations = []
