# Generated by Django 3.2.11 on 2022-05-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0067_alter_programmepage_programme_gallery'),
        ('programmes', '0067_merge_20211027_0806'),
    ]

    operations = [
    ]
