# Generated by Django 3.2.12 on 2022-07-05 10:00

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0067_alter_programmepage_programme_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="working_with",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Collaborator",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(required=False),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="You can add up to 9 collaborators. Minimum 200 x 200 pixels.             Aim for logos that sit on either a white or transparent background.",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="working_with_heading",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
