# Generated by Django 3.2.12 on 2022-07-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("programmes", "0068_adds_quote_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="quote_carousel_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
