# Generated by Django 3.2.12 on 2022-07-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0068_adds_logo_carousel"),
        ("programmes", "0068_merge_20220524_1103"),
    ]

    operations = []
