# Generated by Django 3.2.14 on 2023-02-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0068_adds_logo_carousel'),
        ('programmes', '0069_programmestoriesblock'),
    ]

    operations = [
    ]
