# Generated by Django 3.2.12 on 2022-07-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0068_adds_programme_tags"),
        ("programmes", "0069_merge_20220706_1037"),
    ]

    operations = []
