# Generated by Django 3.2.16 on 2023-02-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0068_adds_programme_tags"),
        ("programmes", "0069_programmestoriesblock"),
    ]

    operations = []
