# Generated by Django 3.2.12 on 2022-07-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0068_adds_quote_carousel"),
        ("programmes", "0070_merge_20220706_1048"),
    ]

    operations = []
