# Generated by Django 3.2.14 on 2023-02-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0070_merge_20230220_1139'),
        ('programmes', '0070_merge_20230227_0204'),
    ]

    operations = [
    ]
