# Generated by Django 3.2.16 on 2023-02-28 01:35

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0071_merge_20230227_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmepage',
            name='notable_alumni_links',
            field=wagtail.fields.StreamField([('Link_to_person', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock(required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
