# Generated by Django 3.2.12 on 2022-07-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0069_add_quote_carousel_link"),
        ("programmes", "0071_merge_20220708_1352"),
    ]

    operations = []
