# Generated by Django 3.2.16 on 2023-03-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0068_adds_quote_carousel'),
        ('programmes', '0072_alter_programmepage_notable_alumni_links'),
    ]

    operations = [
    ]
