# Generated by Django 3.2.14 on 2022-11-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0068_wagtail_3_upgrade"),
        ("programmes", "0072_merge_20220713_1552"),
    ]

    operations = []
