# Generated by Django 3.2.14 on 2022-12-07 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0069_programmestoriesblock'),
        ('programmes', '0073_merge_0068_wagtail_3_upgrade_0072_merge_20220713_1552'),
    ]

    operations = [
    ]
