# Generated by Django 3.2.16 on 2023-03-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0069_add_quote_carousel_link'),
        ('programmes', '0073_merge_20230302_0353'),
    ]

    operations = [
    ]
