# Generated by Django 3.2.16 on 2023-02-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0071_merge_20230227_0246'),
        ('programmes', '0074_merge_20221207_0143'),
    ]

    operations = [
    ]
