# Generated by Django 3.2.16 on 2023-08-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("programmes", "0074_merge_20230302_0516"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepageglobalfieldssettings",
            name="alumni_cta_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Page link",
            ),
        ),
        migrations.AddField(
            model_name="programmepageglobalfieldssettings",
            name="alumni_cta_text",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the page's own title",
                max_length=255,
                verbose_name="Custom link text",
            ),
        ),
    ]
