# Generated by Django 3.2.16 on 2023-03-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0072_alter_programmepage_notable_alumni_links'),
        ('programmes', '0075_merge_20230227_0350'),
    ]

    operations = [
    ]
