# Generated by Django 3.2.16 on 2023-03-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0074_merge_20230302_0516'),
        ('programmes', '0076_merge_20230301_0303'),
    ]

    operations = [
    ]
