# Generated by Django 3.2.16 on 2023-08-16 11:15

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0076_add_video_in_programmepage_requirements_tab"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeStudyMode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammeStudyModeProgrammePage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programme_study_modes",
                        to="programmes.programmepage",
                    ),
                ),
                (
                    "programme_study_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programmes.programmestudymode",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="programmestudymodeprogrammepage",
            constraint=models.UniqueConstraint(
                fields=("page", "programme_study_mode"),
                name="unique_programme_study_mode_per_programme_page",
            ),
        ),
    ]
