# Generated by Django 3.2.16 on 2023-05-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0075_use_json_field'),
        ('programmes', '0077_merge_20230302_0525'),
    ]

    operations = [
    ]
