# Generated by Django 3.2.16 on 2023-08-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0078_data_migration_programme_study_modes_taxonomy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmepage",
            name="programme_details_duration",
        ),
    ]
