# Generated by Django 3.2.16 on 2023-08-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0076_add_video_in_programmepage_requirements_tab"),
        ("programmes", "0078_merge_0075_use_json_field_0077_merge_20230302_0525"),
    ]

    operations = []
