# Generated by Django 3.2.16 on 2023-08-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0079_merge_20230816_0905"),
        ("programmes", "0079_remove_programmepage_programme_details_duration"),
    ]

    operations = []
