# Generated by Django 3.2.16 on 2023-08-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0080_add_alumni_cta_link_to_programmepageglobalfieldssettings"),
        ("programmes", "0080_merge_20230816_1514"),
    ]

    operations = []
