# Generated by Django 3.2.16 on 2023-08-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0080_add_alumni_cta_link_to_programmepageglobalfieldssettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="staff_title",
            field=models.CharField(
                blank=True,
                default="Staff",
                max_length=120,
                verbose_name="Programme staff title",
            ),
        ),
    ]
