# Generated by Django 3.2.16 on 2023-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0081_add_programme_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="staff_title",
            field=models.CharField(
                blank=True,
                default="Staff",
                max_length=120,
                verbose_name="Programme staff title",
            ),
        ),
    ]
