# Generated by Django 3.2.16 on 2023-08-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0081_add_programme_location"),
        ("programmes", "0081_merge_20230817_1103"),
    ]

    operations = []
