# Generated by Django 3.2.16 on 2023-08-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0082_merge_20230818_1233"),
        ("programmes", "0082_programmepage_staff_title"),
    ]

    operations = []
