# Generated by Django 3.2.16 on 2023-09-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0075_use_json_field'),
        ('programmes', '0082_programmepage_staff_title'),
    ]

    operations = [
    ]
