# Generated by Django 3.2.21 on 2023-11-23 08:22

import wagtail.blocks
import wagtail.fields
from django.db import migrations

import rca.navigation.models


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0083_merge_20230918_1445"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="new_quote_carousel_link",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    rca.navigation.models.URLOrRelativeURLBLock(
                                        required=False
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title, required if using a URL",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
