# Generated by Django 3.2.21 on 2023-10-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0083_merge_20230821_1047"),
        ("programmes", "0083_merge_20230918_1445"),
    ]

    operations = []
