# Generated by Django 3.2.21 on 2023-11-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0084_add_social_media_links_to_programmepage"),
        ("programmes", "0084_merge_20231024_0708"),
    ]

    operations = []
