# Generated by Django 3.2.21 on 2023-11-23 08:23

from django.db import migrations
from wagtail.blocks import StreamValue
from wagtail.models import Page


def forwards_func(apps, schema_editor):
    """
    We want to migrate a ForeignKey to a StreamField.
    """
    ProgrammePage = apps.get_model("programmes", "ProgrammePage")
    for page in ProgrammePage.objects.all():
        if page.quote_carousel_link:
            link = page.quote_carousel_link

            stream_data = [
                {
                    "type": "link",
                    "value": {
                        "url": "",
                        "page": link.pk,
                        "title": "Browse our students' experiences",
                    },
                }
            ]
            page.new_quote_carousel_link = StreamValue(
                page.new_quote_carousel_link.stream_block,
                stream_data,
                is_lazy=True,
            )

        # remove the ForeignKey
        page.quote_carousel_link = None

        page.save()


def reverse_func(apps, schema_editor):
    """
    StreamField -> ForeignKey
    """
    ProgrammePage = apps.get_model("programmes", "ProgrammePage")
    for page in ProgrammePage.objects.all():
        if page.new_quote_carousel_link:
            for item in page.new_quote_carousel_link.get_prep_value():
                if item["type"] == "link" and item["value"]["page"]:
                    page.quote_carousel_link_id = item["value"]["page"]
                    page.save()

            # remove the StreamField content
            page.new_quote_carousel_link = []

            page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0084_programmepage_new_quote_carousel_link"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
