# Generated by Django 3.2.21 on 2023-11-23 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0085_data_migration_quote_carousel_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmepage",
            name="quote_carousel_link",
        ),
        migrations.RenameField(
            model_name="programmepage",
            old_name="new_quote_carousel_link",
            new_name="quote_carousel_link",
        ),
    ]
