# Generated by Django 3.2.21 on 2023-11-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0084_add_social_media_links_to_programmepage"),
        ("programmes", "0086_remove_programmepage_quote_carousel_link"),
    ]

    operations = []
