# Generated by Django 3.2.16 on 2023-11-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0087_merge_20231123_1702'),
        ('programmes', '0087_merge_20231124_1110'),
    ]

    operations = [
    ]
