# Generated by Django 4.2.9 on 2024-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0088_django_40_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="staff_summary",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Related staff summary text"
            ),
        ),
    ]
