# Generated by Django 4.2.9 on 2024-01-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0088_django_40_upgrade"),
        ("programmes", "0088_merge_20231127_1719"),
    ]

    operations = []
