# Generated by Django 4.2.9 on 2024-03-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0089_add_book_open_days_title_to_programmepage"),
        ("programmes", "0089_programmepage_staff_summary"),
    ]

    operations = []
