# Generated by Django 4.2.9 on 2024-02-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0089_merge_0088_django_40_upgrade_0088_merge_20231127_1719"),
        ("programmes", "0089_programmepage_staff_summary"),
    ]

    operations = []
