# Generated by Django 4.2.9 on 2024-02-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0089_add_book_open_days_title_to_programmepage"),
        ("programmes", "0090_merge_20240228_1645"),
    ]

    operations = []
