# Generated by Django 4.2.9 on 2024-03-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0090_merge_20240301_1246"),
        ("programmes", "0091_merge_20240229_1055"),
    ]

    operations = []
