# Generated by Django 4.2.11 on 2024-05-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0091_required_title_and_play_button_label_gallery_block"),
        ("programmes", "0092_merge_20240306_1627"),
    ]

    operations = []
