# Generated by Django 4.2.16 on 2025-01-14 14:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0092_link_block_url_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammePageProgrammeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programme_types",
                        to="programmes.programmepage",
                    ),
                ),
                (
                    "programme_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programmes.programmetype",
                    ),
                ),
            ],
        ),
    ]
