# Generated by Django 4.2.17 on 2025-03-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0095_remove_programme_type_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmepage",
            name="mailchimp_group_name",
        ),
    ]
