# Generated by Django 4.2.17 on 2025-04-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0097_alter_programmepage_application_deadline_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmepage",
            name="application_deadline_options",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Applications closed, please check back soon"),
                    ("2", "Still accepting applications"),
                    ("3", "Applications closed"),
                ],
                max_length=1,
            ),
        ),
    ]
