# Generated by Django 4.2.20 on 2025-07-28 18:27

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0098_alter_programmepage_application_deadline_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="experience_content",
            field=wagtail.fields.StreamField(
                [("social_embeds", 1), ("story", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    1: (
                        "wagtail.blocks.StreamBlock",
                        [[("embed", 0)]],
                        {"label": "Social Embeds", "max_num": 12},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The title of the story", "max_length": 255},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Featured image for the story"},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'Article', 'News', 'Feature'",
                            "max_length": 100,
                        },
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to the full story page"},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("image", 3),
                                ("content_type", 4),
                                ("page", 5),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add social embeds (max 12 per block) or editorial page stories",
                verbose_name="Experience Content",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="experience_cta_link",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "rca.navigation.models.URLOrRelativeURLBLock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title, required if using a URL",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 0), ("page", 1), ("title", 2)]],
                        {},
                    ),
                },
                verbose_name="Experience CTA Link",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="experience_introduction",
            field=models.CharField(
                blank=True,
                help_text="Introductory text for the Experience section",
                max_length=500,
            ),
        ),
    ]
