# Generated by Django 4.2.17 on 2025-07-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0098_alter_programmepage_application_deadline_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="vepple_post_id",
            field=models.IntegerField(
                blank=True,
                help_text='NOTE: This is the number from the <code>post="X"</code> part of the embed code provided by Vepple. Wagtail only needs this ID, and will generate the rest of the embed code for you.',
                null=True,
            ),
        ),
    ]
