# Generated by Django 4.2.20 on 2025-07-31 14:05

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0098_alter_programmepage_application_deadline_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="experience_content",
            field=wagtail.fields.StreamField(
                [("social_embeds", 6), ("story", 14)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the social embeds section",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "The embed URL", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The caption for this embed",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The source of this embed (e.g., YouTube, TikTok, Vimeo)",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 1), ("caption", 2), ("embed_source", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {
                            "help_text": "The embeds with captions",
                            "max_num": 12,
                            "min_num": 1,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("embeds", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the stories",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the story",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Featured image for the story", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'Article', 'News', 'Feature'",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to the full story page", "required": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 8),
                                ("image", 9),
                                ("content_type", 10),
                                ("page", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {"help_text": "The stories", "min_num": 1},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("stories", 13)]],
                        {},
                    ),
                },
                help_text="Add social embeds or editorial page stories",
                verbose_name="Experience Content",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="experience_cta_link",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "rca.navigation.models.URLOrRelativeURLBLock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title, required if using a URL",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 0), ("page", 1), ("title", 2)]],
                        {},
                    ),
                },
                verbose_name="Experience CTA Link",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="experience_introduction",
            field=models.TextField(
                blank=True, help_text="Introductory text for the Experience section"
            ),
        ),
    ]
