# Generated by Django 4.2.17 on 2025-07-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0098_alter_programmepage_application_deadline_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="should_display_stories_above_gallery",
            field=models.BooleanField(
                default=False,
                help_text="Checking this will display the programme stories above the programme gallery",
            ),
        ),
    ]
