# Generated by Django 4.2.20 on 2025-07-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0099_programmepage_should_display_stories_above_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmelocationprogrammepage",
            name="programme_location_url",
            field=models.URLField(blank=True),
        ),
    ]
