# Generated by Django 4.2.20 on 2025-08-01 07:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0099_programmepage_should_display_stories_above_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="experience_content",
            field=wagtail.fields.StreamField(
                [("social_embeds", 5), ("story", 12)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    1: ("wagtail.embeds.blocks.EmbedBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The source of this embed (e.g., YouTube, TikTok, Instagram)",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 1), ("caption", 0), ("embed_source", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (3,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("embeds", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g. 'Article', 'News', 'Feature'",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    9: ("wagtail.blocks.PageChooserBlock", (), {"required": True}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("image", 7),
                                ("content_type", 8),
                                ("page", 9),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {"min_num": 1}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("stories", 11)]],
                        {},
                    ),
                },
                help_text="Add social embeds or editorial page stories",
                verbose_name="Experience Content",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="experience_cta_link",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "rca.navigation.models.URLOrRelativeURLBLock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title, required if using a URL",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 0), ("page", 1), ("title", 2)]],
                        {},
                    ),
                },
                verbose_name="Experience CTA Link",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="experience_introduction",
            field=models.TextField(
                blank=True, help_text="Introductory text for the Experience section"
            ),
        ),
    ]
