# Generated by Django 4.2.20 on 2025-08-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0100_add_program_location_url_field"),
        ("programmes", "0100_programmepage_vepple_post_id"),
    ]

    operations = []
