# Generated by Django 4.2.20 on 2025-08-04 02:30

from django.db import migrations, models
import rca.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0101_merge_20250804_0318"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="experience_content",
            field=rca.utils.fields.StreamField(
                blank=True,
                block_lookup={},
                help_text="Add social embeds or editorial page stories",
            ),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="experience_cta_link",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AddField(
            model_name="programmepage",
            name="experience_introduction",
            field=models.TextField(
                blank=True, help_text="Introductory text for the Experience section"
            ),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="facilities_gallery",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="more_information_blocks",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="notable_alumni_links",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="pathway_blocks",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="programme_gallery",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="quote_carousel",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="quote_carousel_link",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="requirements_blocks",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="scholarship_accordion_items",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="scholarship_information_blocks",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="steps",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="what_you_will_cover_blocks",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmepage",
            name="working_with",
            field=rca.utils.fields.StreamField(
                blank=True,
                block_lookup={},
                help_text="You can add up to 9 collaborators. Minimum 200 x 200 pixels.             Aim for logos that sit on either a white or transparent background.",
            ),
        ),
        migrations.AlterField(
            model_name="programmepagefeeitem",
            name="row",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="programmestoriesblock",
            name="slides",
            field=rca.utils.fields.StreamField(block_lookup={}),
        ),
    ]
