# Generated by Django 4.2.23 on 2025-08-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0102_add_experience_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programmetype",
            options={
                "ordering": ["display_name"],
                "verbose_name": "Programme Type",
                "verbose_name_plural": "Programme Types",
            },
        ),
    ]
