# Generated by Django 4.2.20 on 2025-08-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0101_merge_20250801_1016"),
        ("programmes", "0102_add_experience_fields"),
    ]

    operations = []
