# Generated by Django 4.2.27 on 2026-01-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0102_add_experience_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="experience_disclaimer",
            field=models.TextField(
                default="The social media content shown here reflects past and current student activity and is provided for illustrative purposes only. Experiences on the programme may vary and are subject to change for future students."
            ),
            preserve_default=False,
        ),
    ]
