# Generated by Django 4.2.27 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0103_programmepage_experience_disclaimer"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmepage",
            name="exclude_from_programme_finder",
            field=models.BooleanField(
                default=False,
                help_text="Hide this page from the programme finder search results",
            ),
        ),
    ]
