# Generated by Django 4.2.27 on 2026-01-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0103_merge_20250804_0355"),
        ("programmes", "0103_programmepage_experience_disclaimer"),
    ]

    operations = []
