# Generated by Django 5.2.16 on 2026-08-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0104_merge_20260127_0942"),
        ("programmes", "0104_programmepage_exclude_from_programme_finder"),
    ]

    operations = []
