# Generated by Django 5.2.17 on 2026-08-26 05:35

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0104_programmepage_exclude_from_programme_finder"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammePageDegreeLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "qs_code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="This code needs to match the name of the codeExternal value in QS, E.G 105",
                        null=True,
                    ),
                ),
                ("credits", models.CharField(blank=True, max_length=25)),
                (
                    "credits_suffix",
                    models.CharField(
                        blank=True,
                        choices=[("1", "credits"), ("2", "credits at FHEQ Level 6")],
                        max_length=1,
                    ),
                ),
                ("time", models.CharField(blank=True, max_length=25)),
                (
                    "time_suffix",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "year programme"),
                            ("2", "month programme"),
                            ("3", "week programme"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="programmes.degreelevel",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degree_levels",
                        to="programmes.programmepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
