# Generated by Django 5.2.17 on 2026-09-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0105_merge_20260806_1001"),
        ("programmes", "0105_programmepagedegreelevel"),
    ]

    operations = []
