# Generated by Django 5.2.17 on 2026-08-26 05:52

from django.db import migrations


def handle_page(ProgrammePageDegreeLevel, page):
    if not page.degree_level_id:
        return

    already_migrated = ProgrammePageDegreeLevel.objects.filter(
        source_page_id=page.pk,
        level_id=page.degree_level_id,
    ).exists()

    if not already_migrated:
        ProgrammePageDegreeLevel.objects.create(
            source_page_id=page.pk,
            level_id=page.degree_level_id,
            qs_code=page.qs_code,
            credits=page.programme_details_credits,
            credits_suffix=page.programme_details_credits_suffix,
            time=page.programme_details_time,
            time_suffix=page.programme_details_time_suffix,
        )


def handle_revision(page, revision):
    content = revision.content
    degree_level_id = content.get("degree_level")

    if not degree_level_id:
        return

    existing_levels = content.get("degree_levels") or []
    already_migrated = any(
        entry.get("level") == degree_level_id for entry in existing_levels
    )
    if already_migrated:
        return

    content["degree_levels"] = existing_levels + [
        {
            "pk": None,
            "source_page": page.pk,
            "level": degree_level_id,
            "qs_code": content.get("qs_code"),
            "credits": content.get("programme_details_credits"),
            "credits_suffix": content.get("programme_details_credits_suffix"),
            "time": content.get("programme_details_time"),
            "time_suffix": content.get("programme_details_time_suffix"),
            "sort_order": len(existing_levels),
        }
    ]

    revision.content = content
    revision.save(update_fields=["content"])


def handle_page_backward(page):
    first_level = page.degree_levels.order_by("sort_order").first()
    if not first_level:
        return

    fields = {
        "degree_level_id": first_level.level_id,
        "qs_code": first_level.qs_code,
        "programme_details_credits": first_level.credits,
        "programme_details_credits_suffix": first_level.credits_suffix,
        "programme_details_time": first_level.time,
        "programme_details_time_suffix": first_level.time_suffix,
    }

    empty_fields = [name for name in fields if not getattr(page, name)]
    if not empty_fields:
        return

    for name in empty_fields:
        setattr(page, name, fields[name])
    page.save(update_fields=empty_fields)


def handle_revision_backward(revision):
    content = revision.content
    existing_levels = content.get("degree_levels") or []
    if not existing_levels:
        return

    first_level = existing_levels[0]
    fields = {
        "degree_level": first_level.get("level"),
        "qs_code": first_level.get("qs_code"),
        "programme_details_credits": first_level.get("credits"),
        "programme_details_credits_suffix": first_level.get("credits_suffix"),
        "programme_details_time": first_level.get("time"),
        "programme_details_time_suffix": first_level.get("time_suffix"),
    }

    empty_fields = [name for name in fields if not content.get(name)]
    if not empty_fields:
        return

    for name in empty_fields:
        content[name] = fields[name]
    revision.content = content
    revision.save(update_fields=["content"])


def forward(apps, schema_editor):
    ProgrammePage = apps.get_model("programmes", "ProgrammePage")
    ProgrammePageDegreeLevel = apps.get_model("programmes", "ProgrammePageDegreeLevel")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Revision = apps.get_model("wagtailcore", "Revision")

    content_type = ContentType.objects.get_for_model(ProgrammePage)

    for page in ProgrammePage.objects.all():
        handle_page(ProgrammePageDegreeLevel, page)

        for revision in Revision.objects.filter(
            content_type_id=content_type.pk,
            object_id=str(page.pk),
        ):
            handle_revision(page, revision)


def backward(apps, schema_editor):
    ProgrammePage = apps.get_model("programmes", "ProgrammePage")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Revision = apps.get_model("wagtailcore", "Revision")

    content_type = ContentType.objects.get_for_model(ProgrammePage)

    for page in ProgrammePage.objects.all():
        handle_page_backward(page)

        for revision in Revision.objects.filter(
            content_type_id=content_type.pk,
            object_id=str(page.pk),
        ):
            handle_revision_backward(revision)


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0105_programmepagedegreelevel"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
