# Generated by Django 5.2.17 on 2026-08-28 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0106_populate_programmepagedegreelevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmepage",
            name="degree_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="programmes.degreelevel",
            ),
        ),
    ]
