# Generated by Django 5.2.17 on 2026-08-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0107_alter_programmepage_degree_level"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="programmepagedegreelevel",
            constraint=models.UniqueConstraint(
                fields=("source_page", "level"),
                name="unique_degree_level_per_programme_page",
            ),
        ),
    ]
