# Generated by Django 5.2.17 on 2026-08-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "programmes",
            "0108_programmepagedegreelevel_unique_degree_level_per_programme_page",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmepagedegreelevel",
            name="qs_code",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Must match the codeExternal value in QS, e.g. 105. Also required for this degree level to appear on the enquiry form.",
                null=True,
            ),
        ),
    ]
