# Generated by Django 2.2.9 on 2020-03-16 10:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_customimage_file_hash"),
        ("shortcourses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortcoursepage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="shortcoursepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="shortcoursepage",
            name="introduction",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="shortcoursepage",
            name="introduction_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="shortcoursepage",
            name="video",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="shortcoursepage",
            name="video_caption",
            field=models.CharField(
                blank=True,
                help_text="The text dipsplayed next to the video play button",
                max_length=80,
            ),
        ),
    ]
