# Generated by Django 2.2.9 on 2020-03-24 16:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0011_add_short_course_details"),
        ("shortcourses", "0005_access_planit_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortcoursepage",
            name="course_details_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="shortcoursepage",
            name="frequently_asked_questions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utils.ShortCourseDetailSnippet",
            ),
        ),
        migrations.AddField(
            model_name="shortcoursepage",
            name="terms_and_conditions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utils.ShortCourseDetailSnippet",
            ),
        ),
    ]
