# Generated by Django 2.2.9 on 2020-04-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shortcourses", "0007_field_additions_and_related_model")]

    operations = [
        migrations.AddField(
            model_name="shortcoursepage",
            name="hero_colour_option",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Light text on dark image"),
                    (2, "dark text on light image"),
                ],
                default=1,
            ),
            preserve_default=False,
        )
    ]
