# Generated by Django 2.2.9 on 2020-04-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shortcourses", "0008_shortcoursepage_hero_colour_option")]

    operations = [
        migrations.RenameField(
            model_name="shortcourserelatedstaff", old_name="name", new_name="first_name"
        ),
        migrations.AddField(
            model_name="shortcourserelatedstaff",
            name="surname",
            field=models.CharField(default="", max_length=125),
            preserve_default=False,
        ),
    ]
