# Generated by Django 2.2.12 on 2020-04-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0007_swap_for_integer_field"),
        ("shortcourses", "0009_split_name_field_to_first_and_last"),
    ]

    operations = []
