# Generated by Django 2.2.12 on 2020-04-22 10:19

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shortcourses", "0010_merge_20200420_1247")]

    operations = [
        migrations.AlterField(
            model_name="shortcoursepage",
            name="quote_carousel",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "quote",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.core.blocks.CharBlock(
                                        classname="title",
                                        help_text="Enter quote text only, there is no need to add quotation marks",
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "job_title",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Quote carousel",
            ),
        )
    ]
