# Generated by Django 2.2.12 on 2020-04-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shortcourses", "0011_help_text")]

    operations = [
        migrations.AlterField(
            model_name="shortcourserelatedstaff",
            name="description",
            field=models.TextField(
                blank=True, help_text="Not displayed for small teaser profiles"
            ),
        )
    ]
