# Generated by Django 2.2.12 on 2020-05-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0013_add_application_link"),
        ("shortcourses", "0013_add_relationship_to_schools_and_centres"),
    ]

    operations = []
