# Generated by Django 2.2.12 on 2020-05-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0014_merge_20200505_1231"),
        ("shortcourses", "0014_merge_20200504_1623"),
    ]

    operations = []
