# Generated by Django 2.2.12 on 2020-05-06 09:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0053_merge_20200430_0923"),
        ("shortcourses", "0014_merge_20200505_1231"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortCourseSubjectPlacement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="shortcourses.ShortCoursePage",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_course",
                        to="programmes.Subject",
                    ),
                ),
            ],
        )
    ]
