# Generated by Django 2.2.12 on 2020-05-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourses', '0015_merge_20200505_1413'),
        ('shortcourses', '0015_add_subject_relationship'),
    ]

    operations = [
    ]
