# Generated by Django 2.2.12 on 2020-10-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0016_allow_blank_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortcoursepage",
            name="show_register_link",
            field=models.BooleanField(
                default=1,
                help_text="If selected, an automatic 'Register your interest' link will be                                                                    visible in the key details section",
            ),
        ),
    ]
