# Generated by Django 2.2.12 on 2020-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0018_add_manual_bookings"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortcoursepage",
            name="manual_registration_url",
            field=models.URLField(
                blank=True,
                help_text="Override the register interest link show in the modal",
            ),
        ),
    ]
