# Generated by Django 2.2.12 on 2020-10-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0019_manual_register_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortcourse",
            name="booking_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shortcourse",
            name="cost",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shortcourse",
            name="register_interest_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
