# Generated by Django 2.2.12 on 2020-10-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0020_allow_null_values"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShortCourse",
            new_name="ShortCourseManualDate",
        ),
    ]
