# Generated by Django 2.2.12 on 2020-11-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0022_make_booking_link_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortcoursepage",
            name="access_planit_course_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
