# Generated by Django 2.2.12 on 2021-01-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0023_allow_blank_values"),
        ("shortcourses", "0016_merge_20200519_1300"),
    ]

    operations = []
