# Generated by Django 2.2.12 on 2021-01-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0025_remove_old_contact_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortcoursepage",
            name="contact_model_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Contact email"
            ),
        ),
        migrations.AlterField(
            model_name="shortcoursepage",
            name="contact_model_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="forms.FormPage",
                verbose_name="Contact form",
            ),
        ),
        migrations.AlterField(
            model_name="shortcoursepage",
            name="contact_model_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
                verbose_name="Contact image",
            ),
        ),
        migrations.AlterField(
            model_name="shortcoursepage",
            name="contact_model_text",
            field=models.CharField(
                blank=True,
                help_text="Maximum length of 250 characters",
                max_length=250,
                verbose_name="Contact text",
            ),
        ),
        migrations.AlterField(
            model_name="shortcoursepage",
            name="contact_model_title",
            field=models.CharField(
                blank=True,
                help_text="Maximum length of 120 characters",
                max_length=120,
                verbose_name="Contact title",
            ),
        ),
        migrations.AlterField(
            model_name="shortcoursepage",
            name="contact_model_url",
            field=models.URLField(blank=True, verbose_name="Contact url"),
        ),
    ]
