# Generated by Django 2.2.12 on 2021-02-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0026_set_contact_label_names"),
        ("shortcourses", "0024_stop_allowing_blank_pages"),
    ]

    operations = []
