# Generated by Django 2.2.12 on 2021-01-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0024_merge_20210104_1607"),
        ("shortcourses", "0026_set_contact_label_names"),
    ]

    operations = []
