# Generated by Django 2.2.12 on 2021-02-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0027_merge_20210210_0850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortcoursepage",
            name="application_form_url",
            field=models.URLField(
                blank=True,
                help_text="Adding an application form URL will override the Access Planit booking modal",
            ),
        ),
    ]
