# Generated by Django 3.2.16 on 2023-02-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0033_adds_course_page_tags"),
        ("shortcourses", "0033_wagtail_3_upgrade"),
    ]

    operations = []
