# Generated by Django 3.2.14 on 2022-11-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0033_adds_course_page_tags"),
        ("shortcourses", "0033_wagtail_3_upgrade"),
    ]

    operations = []
