# Generated by Django 3.2.16 on 2023-02-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourses', '0034_merge_20221103_1504'),
        ('shortcourses', '0034_merge_20230220_1139'),
    ]

    operations = [
    ]
