# Generated by Django 3.2.16 on 2023-08-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0035_add_embed_to_richtext_in_shortcoursepage_about"),
        ("shortcourses", "0035_merge_20230227_0350"),
    ]

    operations = []
