# Generated by Django 4.2.9 on 2024-01-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0036_django_40_upgrade"),
        ("shortcourses", "0036_merge_20230816_0905"),
    ]

    operations = []
