# Generated by Django 4.2.11 on 2024-10-15 03:20

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0037_required_title_and_play_button_label_gallery_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortcoursepage",
            name="dates",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
