# Generated by Django 4.2.11 on 2024-05-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0037_merge_0036_django_40_upgrade_0036_merge_20230816_0905"),
        ("shortcourses", "0037_required_title_and_play_button_label_gallery_block"),
    ]

    operations = []
