# Generated by Django 4.2.16 on 2025-01-14 14:45

from django.db import migrations


def migrate_programme_type_to_programme_types(apps, schema_editor):
    # Get the models
    ShortCoursePage = apps.get_model("shortcourses", "ShortCoursePage")
    ShortCourseProgrammeType = apps.get_model("shortcourses", "ShortCourseProgrammeType")

    for page in ShortCoursePage.objects.all():
        if programme_type := page.programme_type:
            ShortCourseProgrammeType.objects.create(
                page_id=page.id,
                programme_type=programme_type,
            )

class Migration(migrations.Migration):

    dependencies = [
        ("shortcourses", "0039_shortcourseprogrammetype"),
    ]

    operations = [
        migrations.RunPython(migrate_programme_type_to_programme_types, reverse_code=migrations.RunPython.noop),
    ]
