# Generated by Django 2.2.9 on 2020-04-14 11:35

import django.db.models.deletion
import modelcluster.fields
import phonenumber_field.modelfields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("images", "0002_customimage_file_hash"),
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchcentrepage",
            name="about_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="about_page_link_text",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="about_page_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="centre_address",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="centre_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="centre_news_title",
            field=models.CharField(
                blank=True,
                help_text="The title value displayed above the Research centre news carousel",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="centre_tel",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="hero_colour_option",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Light text on dark image"),
                    (2, "dark text on light image"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="introduction",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="introduction_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="primary_staff_name",
            field=models.CharField(
                blank=True, help_text="The name of the staff member", max_length=250
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="primary_staff_role",
            field=models.CharField(
                blank=True,
                help_text="The role of the staff member, E.G 'Head of Programme'",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="primary_staff_url",
            field=models.URLField(
                blank=True, help_text="The external URL to the staff member page"
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="related_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("url", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Related Links",
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="staff_title",
            field=models.CharField(
                blank=True,
                help_text="The title value displayed above the related staff grid",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="twitter_username",
            field=models.CharField(
                blank=True,
                help_text="The Research Centres Twitter username",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="video",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="researchcentrepage",
            name="video_caption",
            field=models.CharField(
                blank=True,
                help_text="The text dipsplayed next to the video play button",
                max_length=80,
            ),
        ),
        migrations.CreateModel(
            name="ResearchCentrePageStaff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("first_name", models.CharField(max_length=125)),
                ("surname", models.CharField(max_length=125)),
                ("role", models.CharField(blank=True, max_length=125)),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_staff",
                        to="research.ResearchCentrePage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ResearchCentrePageRelatedResearchSpaces",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_spaces",
                        to="research.ResearchCentrePage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ResearchCentrePageRelatedOpportunities",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_opportunities",
                        to="research.ResearchCentrePage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ResearchCentrePageRelatedNews",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_news",
                        to="research.ResearchCentrePage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
    ]
