# Generated by Django 2.2.12 on 2020-04-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("research", "0002_field_additions_and_related_models")]

    operations = [
        migrations.AlterField(
            model_name="researchcentrepagestaff",
            name="description",
            field=models.TextField(
                blank=True, help_text="Not displayed for small teaser profiles"
            ),
        )
    ]
