# Generated by Django 2.2.12 on 2020-04-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("research", "0003_add_all_staff_link")]

    operations = [
        migrations.RenameField(
            model_name="researchcentrepage",
            old_name="centre_news_title",
            new_name="more_research_centre_content_title",
        )
    ]
