# Generated by Django 2.2.12 on 2020-04-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("research", "0003_add_all_staff_link")]

    operations = [
        migrations.AddField(
            model_name="researchcentrepage",
            name="related_programmes_title",
            field=models.CharField(
                default="Related programmes",
                help_text="The title value displayed above the Research centre related_programmes",
                max_length=250,
            ),
            preserve_default=False,
        )
    ]
