# Generated by Django 2.2.12 on 2020-04-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_add_teaser_help_text"),
        ("research", "0004_researchcentrepage_related_programmes_title"),
    ]

    operations = []
