# Generated by Django 2.2.12 on 2020-04-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_merge_20200423_0927"),
        ("research", "0004_rename_news_title_field"),
    ]

    operations = []
