# Generated by Django 2.2.12 on 2020-04-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_merge_20200425_1140"),
        ("research", "0005_merge_20200424_1711"),
        ("research", "0005_merge_20200430_0923"),
    ]

    operations = []
