# Generated by Django 2.2.12 on 2020-04-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_merge_20200427_1158"),
        ("research", "0005_merge_20200425_1140"),
    ]

    operations = []
