# Generated by Django 2.2.12 on 2020-04-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_merge_20200424_1711"),
        ("research", "0006_merge_20200427_1248"),
    ]

    operations = []
