# Generated by Django 2.2.12 on 2020-04-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_merge_20200430_0956"),
        ("research", "0007_merge_20200429_1730"),
    ]

    operations = []
