# Generated by Django 2.2.12 on 2020-05-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_add_configurable_title_field"),
        ("research", "0008_merge_20200430_1001"),
    ]

    operations = []
