# Generated by Django 2.2.12 on 2020-06-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0008_researchcentrepage_legacy_news_and_event_tags"),
        ("research", "0008_improve_relationships_between_models"),
    ]

    operations = []
