# Generated by Django 2.2.12 on 2020-05-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0009_merge_20200504_1723"),
        ("research", "0007_add_curatable_project_relationship"),
    ]

    operations = []
