# Generated by Django 2.2.12 on 2020-06-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0009_merge_20200603_2003"),
        ("research", "0008_merge_20200505_1521"),
    ]

    operations = []
