# Generated by Django 2.2.12 on 2020-06-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0009_merge_20200603_2003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchcentrepage",
            name="primary_staff_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the staff member",
                max_length=250,
                verbose_name="Head of centre full name",
            ),
        ),
        migrations.AlterField(
            model_name="researchcentrepage",
            name="primary_staff_role",
            field=models.CharField(
                blank=True,
                help_text="The role of the staff member, E.G 'Head of Programme'",
                max_length=120,
                verbose_name="Head of centre role",
            ),
        ),
        migrations.AlterField(
            model_name="researchcentrepage",
            name="primary_staff_url",
            field=models.URLField(
                blank=True,
                help_text="The external URL to the staff member page",
                verbose_name="Head of centre URL",
            ),
        ),
    ]
