# Generated by Django 2.2.12 on 2020-06-18 12:04

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0010_field_label_changes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchcentrepage",
            name="legacy_news_and_event_tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Specify one or more tags to identify related news and events from the legacy site. A maximum of three items with the same combination of tags will then be displayed on the page.",
                through="utils.LegacySiteTaggedPage",
                to="utils.LegacySiteTag",
                verbose_name="Legacy news and events tags",
            ),
        ),
    ]
