# Generated by Django 2.2.12 on 2020-06-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0008_improve_relationships_between_models"),
        ("research", "0010_merge_20200505_1044"),
    ]

    operations = []
