# Generated by Django 2.2.12 on 2020-08-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0011_field_label_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchcentrepage",
            name="research_projects_link",
            field=models.URLField(
                blank=True,
                help_text="Add a link to a pre-filtered project listing, E.G https://rca.ac.uk/research/projects/?school-or-centre=helen-hamlyn-centre#results",
            ),
        ),
    ]
