# Generated by Django 2.2.12 on 2020-06-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_merge_20200603_1400'),
        ('research', '0009_merge_20200603_2003'),
    ]

    operations = [
    ]
