# Generated by Django 2.2.12 on 2020-06-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0010_merge_20200615_1410"),
        ("research", "0011_field_label_updates"),
    ]

    operations = []
