# Generated by Django 2.2.12 on 2020-08-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0012_allow_blank_values"),
        ("research", "0012_merge_20200618_1454"),
    ]

    operations = []
