# Generated by Django 2.2.12 on 2020-07-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_field_label_updates'),
        ('research', '0012_merge_20200605_1052'),
    ]

    operations = [
    ]
