# Generated by Django 2.2.12 on 2020-08-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0012_researchcentrepage_research_projects_link"),
        ("research", "0013_merge_20200803_2053"),
    ]

    operations = []
