# Generated by Django 2.2.12 on 2020-08-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0014_merge_20200806_1123"),
        ("research", "0013_merge_20200806_1444"),
    ]

    operations = []
