# Generated by Django 2.2.12 on 2020-10-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0014_tel_display_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchcentrepage",
            name="centre_tel_display_text",
            field=models.CharField(
                blank=True,
                help_text="Specify specific text or numbers to display for the linked tel number, e.g. +44 (0)20 7590 1234 or +44 (0)7749 183783",
                max_length=120,
            ),
        ),
    ]
