# Generated by Django 2.2.12 on 2020-10-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0014_tel_display_field"),
        ("research", "0015_merge_20200806_1855"),
    ]

    operations = []
