# Generated by Django 2.2.12 on 2021-01-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0015_update_help_text"),
        ("research", "0013_merge_20200713_1517"),
    ]

    operations = []
