# Generated by Django 2.2.12 on 2020-10-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0015_update_help_text"),
        ("research", "0016_merge_20201005_1050"),
    ]

    operations = []
