# Generated by Django 3.2.14 on 2022-07-13 16:58

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0017_remove_hero_colour_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchcentrepage",
            name="related_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                ("url", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Related Links",
            ),
        ),
    ]
