# Generated by Django 2.2.12 on 2021-02-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0017_merge_20201006_1127"),
        ("research", "0016_stop_allowing_blank_pages"),
    ]

    operations = []
