# Generated by Django 2.2.12 on 2020-04-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("guides", "0002_guide_base_fields")]

    operations = [
        migrations.AddField(
            model_name="guidepage",
            name="related_pages_title",
            field=models.CharField(blank=True, max_length=120),
        )
    ]
