# Generated by Django 2.2.12 on 2020-04-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("guides", "0003_auto_20200422_1524")]

    operations = [
        migrations.AlterField(
            model_name="guidepagestaff",
            name="description",
            field=models.TextField(
                blank=True, help_text="Not displayed for small teaser profiles"
            ),
        )
    ]
