# Generated by Django 2.2.12 on 2020-04-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0003_add_related_pages_title"),
        ("guides", "0004_auto_20200423_0932"),
    ]

    operations = []
