# Generated by Django 2.2.12 on 2020-05-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("guides", "0006_extra_title_field")]

    operations = []
