# Generated by Django 2.2.12 on 2021-02-23 13:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0013_merge_20210210_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidepage',
            name='body',
            field=wagtail.core.fields.StreamField([('anchor_heading', wagtail.core.blocks.CharBlock(form_classname='full title', icon='title', template='patterns/molecules/streamfield/blocks/anchor_heading_block.html')), ('heading', wagtail.core.blocks.CharBlock(form_classname='full title', icon='title', template='patterns/molecules/streamfield/blocks/heading_block.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(form_classname='title', help_text='Enter quote text only, there is no need to add quotation marks')), ('author', wagtail.core.blocks.CharBlock(required=False)), ('job_title', wagtail.core.blocks.CharBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock(help_text='Add a URL from these providers: YouTube, Vimeo, SoundCloud, Twitter.', label='Embed video'))]),
        ),
    ]
