# Generated by Django 2.2.12 on 2021-02-23 15:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("guides", "0014_embed_video_help_text"),
        ("guides", "0015_embed_video_help_text"),
    ]

    dependencies = [
        ("guides", "0013_merge_20210210_0850"),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidepage',
            name='body',
            field=wagtail.fields.StreamField([('anchor_heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title', template='patterns/molecules/streamfield/blocks/anchor_heading_block.html')), ('heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title', template='patterns/molecules/streamfield/blocks/heading_block.html')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False))])), ('quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.CharBlock(form_classname='title', help_text='Enter quote text only, there is no need to add quotation marks')), ('author', wagtail.blocks.CharBlock(required=False)), ('job_title', wagtail.blocks.CharBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock(help_text='Add a URL from these providers: YouTube, Vimeo, SoundCloud, Twitter.', label='Embed video'))]),
        ),
        migrations.AlterField(
            model_name='guidepage',
            name='body',
            field=wagtail.fields.StreamField([('anchor_heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title', template='patterns/molecules/streamfield/blocks/anchor_heading_block.html')), ('heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title', template='patterns/molecules/streamfield/blocks/heading_block.html')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False))])), ('quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.CharBlock(form_classname='title', help_text='Enter quote text only, there is no need to add quotation marks')), ('author', wagtail.blocks.CharBlock(required=False)), ('job_title', wagtail.blocks.CharBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock(help_text='Add a URL from these providers: YouTube, Vimeo, SoundCloud, Twitter.', label='Embed media'))]),
        ),
    ]
