# Generated by Django 3.1.10 on 2021-07-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0020_add_tap_widget_snippet"),
        ("guides", "0014_embed_video_help_text_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidepage",
            name="tap_widget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="utils.tapwidgetsnippet",
            ),
        ),
    ]
