# Generated by Django 4.2.11 on 2024-09-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0025_add_vepple_panorama_block"),
        ("guides", "0025_cta_link_block"),
    ]

    operations = []
