# Generated by Django 4.2.11 on 2024-10-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0027_link_block_url_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidepage",
            name="related_staff_title",
            field=models.CharField(blank=True, default="Staff", max_length=120),
        ),
    ]
