# Generated by Django 4.2.16 on 2025-01-13 14:55

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0029_accordion_streamfield_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidepage",
            name="further_information_block",
            field=wagtail.fields.StreamField(
                [("accordion", 9)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A large heading diplayed next to the block",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The text to display when the accordion is collapsed",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "image",
                                "embed",
                                "ul",
                                "ol",
                                "link",
                            ],
                            "help_text": "The content shown when the accordion expanded",
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("url", 5)]],
                        {
                            "help_text": "An optional link to display below the expanded content",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 1),
                                ("preview_text", 2),
                                ("body", 3),
                                ("link", 6),
                            ]
                        ],
                        {},
                    ),
                    8: ("wagtail.blocks.ListBlock", (7,), {}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("items", 8)]],
                        {},
                    ),
                },
            ),
        ),
    ]
