# Generated by Django 4.2.16 on 2025-01-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0031_migrate_further_information_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guidepage",
            name="further_information",
        ),
        migrations.RemoveField(
            model_name="guidepage",
            name="further_information_title",
        ),
    ]
