# Generated by Django 4.2.17 on 2025-07-30 03:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0032_remove_old_further_information_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("anchor_heading", 0),
                    ("heading", 1),
                    ("paragraph", 2),
                    ("image", 6),
                    ("quote", 8),
                    ("embed", 9),
                    ("image_video_gallery", 15),
                    ("table", 20),
                    ("jw_video", 24),
                    ("vepple_panorama", 26),
                    ("cookie_snippet_block", 27),
                    ("cta_link", 31),
                    ("accordion", 39),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/anchor_heading_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/heading_block.html",
                        },
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Toggle to make image decorative so they can be ignored by assistive technologies.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("caption", 4), ("decorative", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "help_text": "Enter quote text only, there is no need to add quotation marks",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 7), ("author", 4), ("job_title", 4)]],
                        {},
                    ),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Add a URL from these providers: YouTube, Vimeo, SoundCloud, Twitter.",
                            "label": "Embed media",
                        },
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {}),
                    11: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Add a link to embed a video. Leave blank to only display an image.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The text displayed below the video.",
                            "label": "Caption",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 3),
                                ("video_embed", 11),
                                ("embed_play_button_label", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.blocks.StreamBlock", [[("item", 13)]], {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 10), ("image_video", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    17: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "The first row of columns are headers",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "The first column of each row is a header",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("table", 17),
                                ("first_row_is_header", 18),
                                ("first_col_is_header", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title to identify the video. Not shown on the page.",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "The URL of the video to show.",
                            "max_length": 1000,
                        },
                    ),
                    23: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "The poster image to show as a placeholder for the video. For best results use an image 1920x1080 pixels"
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 21), ("video_url", 22), ("poster_image", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": 'NOTE: This is the number from the <code>post="X"</code> part of the embed code provided by Vepple. Wagtail only needs this ID, and will generate the rest of the embed code for you.',
                            "label": "Post ID",
                        },
                    ),
                    26: ("wagtail.blocks.StructBlock", [[("post_id", 25)]], {}),
                    27: (
                        "rca.utils.blocks.embeds.CookieSnippetBlock",
                        ("utils.CookieButtonSnippet",),
                        {},
                    ),
                    28: (
                        "rca.navigation.models.URLOrRelativeURLBLock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    29: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title, required if using a URL",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 28), ("page", 29), ("title", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A large heading diplayed next to the block",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The text to display when the accordion is collapsed",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "image",
                                "embed",
                                "ul",
                                "ol",
                                "link",
                            ],
                            "help_text": "The content shown when the accordion expanded",
                        },
                    ),
                    35: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("url", 35)]],
                        {
                            "help_text": "An optional link to display below the expanded content",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 32),
                                ("preview_text", 33),
                                ("body", 34),
                                ("link", 36),
                            ]
                        ],
                        {},
                    ),
                    38: ("wagtail.blocks.ListBlock", (37,), {}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 10), ("items", 38)]],
                        {},
                    ),
                },
            ),
        ),
    ]
