# Generated by Django 4.2.20 on 2025-08-04 02:20

from django.db import migrations
import rca.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0033_add_image_video_gallery_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidepage",
            name="body",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="further_information_block",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
    ]
