language: python
python:
  - 3.6
cache:
  pip: true
  directories:
    - node_modules

# Use container-based infrastructure
dist: trusty
sudo: false

# Services
services:
  - postgresql

addons:
  postgresql: '9.6'

env:
  global:
    - DJANGO_SETTINGS_MODULE=rca.settings.production
    - DATABASE_URL=postgres://postgres@localhost/test_db
    - SECRET_KEY=iamnotsosecret
    - ALLOWED_HOSTS=localhost

before_script:
  # Create a database
  - psql -c 'create database test_db;' -U postgres

# Package installation
install:
  # Install project dependencies
  - pip install -r requirements.txt

  # Install test dependencies
  - pip install flake8

  # Install node
  - nvm install 12

  # Install node dependencies
  - npm ci

  # Build the static files
  - npm run build:prod

# Run the tests
script:
  # Run python code style checks
  - flake8 rca

  # Run JS code style checks
  - npm run lint:js

  # Run CSS code style checks
  - npm run lint:css

  # Run formatting code style checks
  - npm run lint:format

  # Run system checks
  - python manage.py check

  # Check for missing migrations
  - python manage.py makemigrations --check

  # Run back-end tests
  - python manage.py test

  # Run front-end tests
  - npm run test:coverage
