site_name: RCA
repo_url: https://github.com/torchbox/rca-wagtail-2019
repo_name: Gitlab
dev_addr: 0.0.0.0:8001
theme:
  name: 'material'
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true

nav:
  - 'Home': 'index.md'
  - 'Front end tooling': 'front-end-tooling.md'
  - Implementation Specs:
      - 'Rebuild Approach': 'implementation-specs/finalised-rebuild-approach.md'
      - 'Programme Page': 'implementation-specs/programme-page.md'
      - 'Content relationship via API': 'implementation-specs/content-relationships.md'
      - 'Support runbook': 'support-runbook.md'
      - 'Upgrading guidelines': 'upgrading.md'
      - 'Anonymising data': 'anonymised-data.md'
