context:
  page:
    requirements_subtitle: 'What you need to know before you apply'
    requirements_text: 'Candidates for all MA programmes are assessed on their existing qualities as demonstrated in their work and in their interview, as well as on their potential to benefit from the programme and to achieve MA standards overall.'
