# Generated by Django 2.0.9 on 2018-10-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("images", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="file_hash",
            field=models.CharField(blank=True, editable=False, max_length=40),
        )
    ]
