# Generated by Django 3.2.12 on 2022-06-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_extends_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
    ]
