# Generated by Django 4.2.17 on 2025-01-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_alter_customimage_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
