# Generated by Django 2.2.9 on 2020-03-13 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("standardpages", "0002_set_related_pages_to_cascade")]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "indexpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="standardpages.IndexPage",
                    ),
                )
            ],
            options={"abstract": False},
            bases=("standardpages.indexpage",),
        )
    ]
