# Generated by Django 2.2.9 on 2020-04-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0003_capitalizeverbose"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtailsearchpromotions", "0002_capitalizeverbose"),
        ("standardpages", "0003_landingpage"),
    ]

    operations = [
        migrations.DeleteModel(name="LandingPage",),
    ]
