# Generated by Django 2.2.9 on 2020-04-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0004_delete_landingpage"),
        ("standardpages", "0004_body_update"),
    ]

    operations = []
