# Generated by Django 3.2.11 on 2022-05-23 14:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('standardpages', '0007_alter_informationpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', icon='title', template='patterns/molecules/streamfield/blocks/heading_block.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(form_classname='title', help_text='Enter quote text only, there is no need to add quotation marks')), ('author', wagtail.core.blocks.CharBlock(required=False)), ('job_title', wagtail.core.blocks.CharBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('call_to_action', wagtail.snippets.blocks.SnippetChooserBlock('utils.CallToActionSnippet', template='patterns/molecules/streamfield/blocks/call_to_action_block.html')), ('document', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock())])), ('jw_video', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Optional title to identify the video. Not shown on the page.', required=False)), ('video_url', wagtail.core.blocks.URLBlock(help_text='The URL of the video to show.', max_length=1000)), ('poster_image', wagtail.images.blocks.ImageChooserBlock(help_text='The poster image to show as a placeholder for the video. For best results use an image 1920x1080 pixels'))]))]),
        ),
    ]
