# Generated by Django 4.2.20 on 2025-09-19 00:26

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0009_decorative_option_image_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 5),
                    ("quote", 7),
                    ("embed", 8),
                    ("call_to_action", 9),
                    ("document", 11),
                    ("livestream_video", 15),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/heading_block.html",
                        },
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Toggle to make image decorative so they can be ignored by assistive technologies.",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3), ("decorative", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "help_text": "Enter quote text only, there is no need to add quotation marks",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 6), ("author", 3), ("job_title", 3)]],
                        {},
                    ),
                    8: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    9: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.CallToActionSnippet",),
                        {
                            "template": "patterns/molecules/streamfield/blocks/call_to_action_block.html"
                        },
                    ),
                    10: ("wagtail.documents.blocks.DocumentChooserBlock", (), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("document", 10), ("title", 3)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title to identify the video. Not shown on the page.",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "The URL of the video to show.",
                            "label": "Video URL",
                            "max_length": 1000,
                        },
                    ),
                    14: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "The poster image to show as a placeholder for the video. For best results use an image 1920x1080 pixels"
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("video_url", 13), ("poster_image", 14)]],
                        {},
                    ),
                },
            ),
        ),
    ]
