# Generated by Django 3.1.7 on 2021-04-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_student_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"]},
        ),
    ]
