# Generated by Django 2.2.3 on 2019-08-06 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("navigation", "0002_add_new_menu_structure_and_links")]

    operations = [
        migrations.RemoveField(
            model_name="navigationsettings", name="secondary_navigation"
        )
    ]
