# Generated by Django 4.2.14 on 2024-08-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0006_wagtail_3_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsettings",
            name="last_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
