# Generated by Django 4.2.11 on 2024-09-20 07:14

from django.db import migrations
import rca.navigation.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0007_navigationsettings_last_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    rca.navigation.models.URLOrRelativeURLBLock(
                                        label="URL", required=False
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title, required if using a URL",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Single list of elements at the base of the page.",
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_navigation",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    rca.navigation.models.URLOrRelativeURLBLock(
                                        label="URL", required=False
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title, required if using a URL",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Multiple columns of footer links with optional header.",
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "primary_link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "url",
                                                rca.navigation.models.URLOrRelativeURLBLock(
                                                    label="URL", required=False
                                                ),
                                            ),
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Leave blank to use the page's own title, required if using a URL",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Top level menu links",
                                    ),
                                ),
                                (
                                    "secondary_links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "url",
                                                    rca.navigation.models.URLOrRelativeURLBLock(
                                                        label="URL", required=False
                                                    ),
                                                ),
                                                (
                                                    "page",
                                                    wagtail.blocks.PageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Leave blank to use the page's own title, required if using a URL",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "tertiary_links",
                                                    wagtail.blocks.ListBlock(
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "url",
                                                                    rca.navigation.models.URLOrRelativeURLBLock(
                                                                        label="URL",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "page",
                                                                    wagtail.blocks.PageChooserBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Leave blank to use the page's own title, required if using a URL",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        )
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Main site navigation",
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="quick_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    rca.navigation.models.URLOrRelativeURLBLock(
                                        label="URL", required=False
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title, required if using a URL",
                                        required=False,
                                    ),
                                ),
                                ("sub_text", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
