# Generated by Django 2.2.9 on 2020-04-14 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("images", "0002_customimage_file_hash"),
        ("wagtailforms", "0003_capitalizeverbose"),
        ("wagtailsearchpromotions", "0002_capitalizeverbose"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("landingpages", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InovationLandingPage", new_name="InnovationLandingPage"
        )
    ]
