# Generated by Django 2.2.12 on 2020-04-28 14:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_extends_image_fields"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("landingpages", "0002_rename_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enterpriselandingpage",
            options={"verbose_name": "Landing Page - Enterprise"},
        ),
        migrations.AlterModelOptions(
            name="innovationlandingpage",
            options={"verbose_name": "Landing Page - Innovation"},
        ),
        migrations.AlterModelOptions(
            name="researchlandingpage",
            options={"verbose_name": "Landing Page - Research"},
        ),
        migrations.AddField(
            model_name="landingpage",
            name="about_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="hero_colour_option",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Light text on dark image"),
                    (2, "dark text on light image"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landingpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="highlights_link_text",
            field=models.CharField(
                blank=True, help_text="The text to display for the link", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="highlights_link_url",
            field=models.URLField(
                blank=True, help_text="Optional link to more information"
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="highlights_title",
            field=models.TextField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="introduction",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="related_pages_list_subtitle",
            field=models.TextField(
                blank=True,
                help_text="The subtitle, displayed above the related pages",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="related_pages_list_title",
            field=models.TextField(
                blank=True,
                help_text="The title to be displayed above the related pages",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="related_pages_text",
            field=models.TextField(
                blank=True,
                help_text="The brief paragraph of text to be displayed above the related pages grid",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="related_pages_title",
            field=models.TextField(
                blank=True,
                help_text="The title to be displayed above the related pages grid",
                max_length=80,
            ),
        ),
        migrations.CreateModel(
            name="LandingPageRelatedPageList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_pages_list",
                        to="landingpages.LandingPage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandingPageRelatedPageHighlights",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_pages_highlights",
                        to="landingpages.LandingPage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandingPageRelatedPagegrid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_pages_grid",
                        to="landingpages.LandingPage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandingPageFeaturedImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                ("link_text", models.CharField(blank=True, max_length=255)),
                ("title", models.TextField(blank=True, max_length=80)),
                ("subtitle", models.TextField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True, max_length=250)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_image",
                        to="landingpages.LandingPage",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
