# Generated by Django 2.2.12 on 2020-04-25 14:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_customimage_file_hash"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("landingpages", "0002_rename_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPageDefault",
            fields=[
                (
                    "landingpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="landingpages.LandingPage",
                    ),
                ),
                (
                    "related_pages_title",
                    models.TextField(
                        blank=True,
                        help_text="The title to be displayed above the related pages grid",
                        max_length=80,
                    ),
                ),
                (
                    "related_pages_text",
                    models.TextField(
                        blank=True,
                        help_text="The brief paragraph of text to be displayed above the related pages grid",
                        max_length=250,
                    ),
                ),
                (
                    "related_programmes_title",
                    models.TextField(
                        blank=True,
                        help_text="The title to be displayed above the related pages",
                        max_length=80,
                    ),
                ),
                (
                    "related_programmes_subtitle",
                    models.TextField(
                        blank=True,
                        help_text="The subtitle, displayed above the related pages",
                        max_length=80,
                    ),
                ),
            ],
            options={"verbose_name": "Landing Page - Default"},
            bases=("landingpages.landingpage",),
        ),
        migrations.AlterModelOptions(
            name="enterpriselandingpage",
            options={"verbose_name": "Landing Page - Enterprise"},
        ),
        migrations.AlterModelOptions(
            name="innovationlandingpage",
            options={"verbose_name": "Landing Page - Innovation"},
        ),
        migrations.AlterModelOptions(
            name="researchlandingpage",
            options={"verbose_name": "Landing Page - Research"},
        ),
        migrations.AddField(
            model_name="landingpage",
            name="hero_colour_option",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Light text on dark image"),
                    (2, "dark text on light image"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landingpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="highlights_title",
            field=models.TextField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="introduction",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="LandingPageHighlightLinkField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                ("link_text", models.CharField(blank=True, max_length=255)),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlight_link",
                        to="landingpages.LandingPage",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="LandingPageDefaultRelatedProgrammPages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_programmes",
                        to="landingpages.LandingPageDefault",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandingPageDefaultRelatedProgrammesLinkField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                ("link_text", models.CharField(blank=True, max_length=255)),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_programmes_link",
                        to="landingpages.LandingPageDefault",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="LandingPageDefaultRelatedPages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_pages",
                        to="landingpages.LandingPageDefault",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandingPageDefaultHighlightPages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlight_pages_default",
                        to="landingpages.LandingPageDefault",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LandingPageDefaultFeaturedImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                ("link_text", models.CharField(blank=True, max_length=255)),
                ("title", models.TextField(blank=True, max_length=80)),
                ("subtitle", models.TextField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True, max_length=250)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_image",
                        to="landingpages.LandingPageDefault",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="LandingPageAboutLinkField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                ("link_text", models.CharField(blank=True, max_length=255)),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_page",
                        to="landingpages.LandingPage",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
