# Generated by Django 2.2.12 on 2020-04-28 16:13

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("landingpages", "0003_auto_20200428_1538")]

    operations = [
        migrations.RemoveField(
            model_name="landingpage", name="related_pages_list_subtitle"
        ),
        migrations.RemoveField(
            model_name="landingpage", name="related_pages_list_title"
        ),
        migrations.AddField(
            model_name="landingpage",
            name="page_list",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page_list",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="A large heading diplayed at the top of block",
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="An optional link to display below the expanded content",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="page_list_title",
            field=models.TextField(
                blank=True,
                help_text="The title to be displayed above the page list blocks",
                max_length=80,
            ),
        ),
        migrations.DeleteModel(name="LandingPageRelatedPageList"),
    ]
