# Generated by Django 2.2.12 on 2020-04-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("landingpages", "0008_fix_link_block_title")]

    operations = [
        migrations.AlterField(
            model_name="homepageslideshowblock",
            name="summary",
            field=models.CharField(blank=True, max_length=250),
        )
    ]
