# Generated by Django 2.2.12 on 2020-05-04 13:50

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("landingpages", "0012_swap_for_page_chooser")]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="page_list",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page_list",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="A large heading diplayed at the top of block",
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="An optional link to display below the expanded content",
                                        required=False,
                                    ),
                                ),
                                (
                                    "page_link",
                                    wagtail.blocks.PageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        )
    ]
