# Generated by Django 2.2.12 on 2020-06-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0016_landingpage_legacy_news_and_event_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="highlights_page_link_title",
            field=models.TextField(
                blank=True, help_text="The text do display for the link", max_length=120
            ),
        ),
    ]
