# Generated by Django 2.2.12 on 2020-06-18 10:57

import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0017_landingpage_highlights_page_link_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="cta_block",
            field=wagtail.fields.StreamField(
                [
                    (
                        "call_to_action",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="A large heading diplayed at the top of block",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="An optional link to display below the expanded content",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="text promo",
                        ),
                    )
                ],
                blank=True,
                verbose_name="Text promo",
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="highlights_page_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.Page",
                verbose_name="Featured projects link",
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="highlights_title",
            field=models.TextField(
                blank=True,
                help_text="Maximum length of 80 characters",
                max_length=80,
                verbose_name="Featured projects title",
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="legacy_news_and_event_tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Specify one or more tags to identify related news and events from the legacy site. A maximum of three items with the same combination of tags will then be displayed on the page.",
                through="utils.LegacySiteTaggedPage",
                to="utils.LegacySiteTag",
                verbose_name="Legacy news and events tags",
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="slideshow_summary",
            field=models.CharField(
                blank=True,
                help_text="Maximum length of 250 characters",
                max_length=250,
                verbose_name="Related content summary",
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="slideshow_title",
            field=models.CharField(
                blank=True,
                help_text="Maximum length of 125 characters",
                max_length=125,
                verbose_name="Related content title",
            ),
        ),
    ]
