# Generated by Django 2.2.12 on 2020-06-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0018_field_label_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="highlights_page_link_title",
            field=models.TextField(
                blank=True,
                help_text="The text do display for the link",
                max_length=120,
                verbose_name="Featured projects link title",
            ),
        ),
    ]
