# Generated by Django 3.1.10 on 2021-07-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0024_remove_hero_colour_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TapLandingPage",
            fields=[
                (
                    "landingpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="landingpages.landingpage",
                    ),
                ),
                (
                    "tap_carousel",
                    models.TextField(blank=True, verbose_name="Iframe Code"),
                ),
            ],
            options={"verbose_name": "Landing Page - TAP",},
            bases=("landingpages.landingpage",),
        ),
    ]
