# Generated by Django 3.1.10 on 2021-07-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0020_add_tap_widget_snippet"),
        ("landingpages", "0025_add_tap_landing_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="tap_widget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="utils.tapwidgetsnippet",
            ),
        ),
    ]
