# Generated by Django 3.1.10 on 2021-07-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0026_eelandingpage"),
        ("landingpages", "0027_add_tap_widget_landing_page"),
    ]

    operations = []
