# Generated by Django 3.1.10 on 2021-07-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0027_add_related_news"),
        ("landingpages", "0028_merge_20210722_1754"),
    ]

    operations = []
