# Generated by Django 3.1.10 on 2021-07-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_extends_image_fields"),
        ("landingpages", "0029_add_related_stories"),
    ]

    operations = [
        migrations.AddField(
            model_name="eelandingpage",
            name="talks_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="eelandingpage",
            name="talks_link_target_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eelandingpage",
            name="talks_link_text",
            field=models.TextField(
                default="", help_text="The text do display for the link", max_length=120
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eelandingpage",
            name="talks_summary_text",
            field=models.TextField(
                default="",
                help_text="Short text summary displayed with the 'Talks' title",
                max_length=250,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eelandingpage",
            name="video",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="eelandingpage",
            name="video_caption",
            field=models.CharField(
                blank=True,
                help_text="The text displayed next to the video play button",
                max_length=80,
            ),
        ),
    ]
