# Generated by Django 3.1.10 on 2021-07-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0032_adds_cta_block"),
        ("landingpages", "0029_merge_20210723_1525"),
    ]

    operations = []
