# Generated by Django 3.1.10 on 2021-08-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0032_adds_cta_block"),
        ("landingpages", "0027_add_tap_widget_landing_page"),
    ]

    operations = []
