# Generated by Django 3.1.10 on 2021-08-10 13:32

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_extends_image_fields"),
        ("landingpages", "0032_adds_cta_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniLandingPage",
            fields=[
                (
                    "landingpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="landingpages.landingpage",
                    ),
                ),
                ("location", wagtail.fields.RichTextField(blank=True)),
                (
                    "social_links",
                    wagtail.fields.StreamField(
                        [
                            (
                                "Link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "video_caption",
                    models.CharField(
                        blank=True,
                        help_text="The text displayed next to the video play button",
                        max_length=80,
                    ),
                ),
                ("video", models.URLField(blank=True)),
                (
                    "video_preview_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("landingpages.landingpage",),
        ),
    ]
