# Generated by Django 3.1.10 on 2021-08-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0033_merge_20210803_1110"),
        ("landingpages", "0033_merge_20210726_1424"),
    ]

    operations = []
