# Generated by Django 3.1.10 on 2021-08-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0033_alumnilandingpage"),
        ("landingpages", "0034_merge_20210803_1126"),
    ]

    operations = []
