# Generated by Django 3.1.10 on 2021-08-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0035_merge_20210811_1016"),
        ("landingpages", "0034_add_collaborators_and_cta"),
    ]

    operations = []
