# Generated by Django 3.1.10 on 2021-08-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0035_related_editorial_sections_and_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumnilandingpage",
            name="news_link_target_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alumnilandingpage",
            name="news_link_text",
            field=models.TextField(
                default="", help_text="The text do display for the link", max_length=120
            ),
            preserve_default=False,
        ),
    ]
