# Generated by Django 3.1.10 on 2021-08-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0036_alumni_related_pages_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumnilandingpage",
            name="collaborators_heading",
            field=models.CharField(
                blank=True,
                help_text="The text displayed above the collaborators carousel",
                max_length=80,
            ),
        ),
    ]
