# Generated by Django 3.1.10 on 2021-08-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0036_merge_20210811_1909"),
        ("landingpages", "0035_related_editorial_sections_and_fields"),
    ]

    operations = []
