# Generated by Django 3.1.10 on 2021-08-18 10:56

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations

import rca.navigation.models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0036_adds_link_fields_for_news"),
    ]

    operations = [
        migrations.RemoveField(model_name="alumnilandingpage", name="external_links",),
        migrations.AddField(
            model_name="alumnilandingpage",
            name="additional_links",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    rca.navigation.models.URLOrRelativeURLBLock(
                                        required=False
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.core.blocks.PageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title, required if using a URL",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Additional Links",
            ),
        ),
    ]
