# Generated by Django 3.1.10 on 2021-08-18 11:22

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models

import rca.navigation.models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0037_adds_collaborators_heading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumnilandingpage",
            name="external_links",
        ),
        migrations.AddField(
            model_name="alumnilandingpage",
            name="additional_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    rca.navigation.models.URLOrRelativeURLBLock(
                                        required=False
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title, required if using a URL",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Additional Links",
            ),
        ),
        migrations.AddField(
            model_name="alumnilandingpage",
            name="news_link_target_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alumnilandingpage",
            name="news_link_text",
            field=models.TextField(
                default="", help_text="The text do display for the link", max_length=120
            ),
            preserve_default=False,
        ),
    ]
