# Generated by Django 3.1.10 on 2021-08-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0036_alumni_related_pages_carousel"),
        ("landingpages", "0037_merge_20210811_1920"),
    ]

    operations = []
