# Generated by Django 3.1.10 on 2021-08-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0038_merge_20210814_0141"),
        ("landingpages", "0037_adds_collaborators_heading"),
    ]

    operations = []
