# Generated by Django 3.1.10 on 2021-08-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "landingpages",
            "0038_adds_heading_and_swaps_external_links_for_additional_links",
        ),
        ("landingpages", "0039_merge_20210818_1059"),
    ]

    operations = []
