# Generated by Django 3.1.10 on 2021-08-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0039_developmentlandingpage"),
        ("landingpages", "0040_merge_20210819_0433"),
    ]

    operations = []
