# Generated by Django 3.1.10 on 2021-08-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0041_development_landing_story_pages_and_cta"),
    ]

    operations = [
        migrations.AddField(
            model_name="eelandingpage",
            name="cta_navigation_title",
            field=models.CharField(
                default="Media centre",
                help_text="The text displayed for this section in the in-page navigation",
                max_length=80,
            ),
            preserve_default=False,
        ),
    ]
