# Generated by Django 3.1.10 on 2021-08-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0040_dev_related_pages_and_extra_cta"),
        ("landingpages", "0041_merge_20210819_0818"),
    ]

    operations = []
