# Generated by Django 3.1.10 on 2021-08-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0041_development_landing_story_pages_and_cta"),
        ("landingpages", "0042_merge_20210820_0343"),
    ]

    operations = []
