# Generated by Django 3.1.10 on 2021-08-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0042_add_menu_item_field"),
        ("landingpages", "0043_merge_20210820_0853"),
    ]

    operations = []
