# Generated by Django 3.1.10 on 2021-09-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0043_relatedlandingpage"),
        ("landingpages", "0033_merge_20210803_1110"),
    ]

    operations = []
