# Generated by Django 3.1.10 on 2021-08-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0044_merge_20210824_0823"),
        ("landingpages", "0043_relatedlandingpage"),
    ]

    operations = []
