# Generated by Django 3.1.10 on 2021-09-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0045_merge_20210827_0145"),
        ("landingpages", "0044_merge_20210910_1128"),
    ]

    operations = []
