# Generated by Django 3.2.12 on 2022-07-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0045_adds_news_and_event_link_fields"),
        ("landingpages", "0046_merge_20210927_1519"),
    ]

    operations = []
