# Generated by Django 3.2.14 on 2023-02-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0045_adds_news_and_event_link_fields'),
        ('landingpages', '0046_alumnilandingpageteaser'),
    ]

    operations = [
    ]
