# Generated by Django 3.2.14 on 2022-11-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0045_wagtail_3_upgrade"),
        ("landingpages", "0047_merge_20220712_0957"),
    ]

    operations = []
