# Generated by Django 4.2.20 on 2025-11-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0048_link_block_url_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eelandingpage",
            old_name="talks_image",
            new_name="podcasts_image",
        ),
        migrations.RenameField(
            model_name="eelandingpage",
            old_name="talks_link_target_url",
            new_name="podcasts_link_target_url",
        ),
        migrations.RenameField(
            model_name="eelandingpage",
            old_name="talks_link_text",
            new_name="podcasts_link_text",
        ),
        migrations.RenameField(
            model_name="eelandingpage",
            old_name="talks_summary_text",
            new_name="podcasts_summary_text",
        ),
        migrations.AlterField(
            model_name="eelandingpage",
            name="podcasts_summary_text",
            field=models.TextField(
                help_text="Short text summary displayed with the 'Podcasts' title",
                max_length=250,
            ),
        ),
    ]
