# Generated by Django 3.2.14 on 2022-12-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0046_alumnilandingpageteaser'),
        ('landingpages', '0048_merge_0045_wagtail_3_upgrade_0047_merge_20220712_0957'),
    ]

    operations = [
    ]
