# Generated by Django 3.2.16 on 2023-02-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0047_merge_20230227_0237'),
        ('landingpages', '0049_merge_20221212_0948'),
    ]

    operations = [
    ]
