# Generated by Django 2.2.3 on 2019-08-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("utils", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="socialmediasettings",
            name="instagram",
            field=models.CharField(
                blank=True, help_text="Your Instagram username.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="socialmediasettings",
            name="linkedin_url",
            field=models.URLField(
                blank=True, help_text="Your full Linked in page url."
            ),
        ),
        migrations.AddField(
            model_name="socialmediasettings",
            name="youtube",
            field=models.CharField(
                blank=True, help_text="Your YouTube username.", max_length=255
            ),
        ),
    ]
