# Generated by Django 2.2.4 on 2019-09-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("utils", "0003_socialmediasettings_facebook_page_name")]

    operations = [
        migrations.CreateModel(
            name="FacilitiesSnippet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_title",
                    models.CharField(
                        help_text="The title value is only used to identify the snippet in the admin interface ",
                        max_length=255,
                    ),
                ),
                ("introduction", models.CharField(max_length=255)),
                ("copy", models.TextField(blank=True)),
            ],
        )
    ]
