# Generated by Django 2.2.4 on 2019-09-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("utils", "0009_add_apply_tab_control")]

    operations = [
        migrations.AlterField(
            model_name="programmesettings",
            name="disable_apply_tab",
            field=models.BooleanField(
                default=0,
                help_text="This setting will remove the apply tab from all programme pages. This setting overrides the same setting applied at the individual programme page level.",
            ),
        )
    ]
