# Generated by Django 2.2.12 on 2020-06-12 13:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("utils", "0010_update_help_texts"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitewideAlertSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_alert",
                    models.BooleanField(
                        default=False,
                        help_text="Checking this will show the site-wide message",
                    ),
                ),
                (
                    "message",
                    wagtail.fields.RichTextField(
                        help_text="The message to be shown to all users across the site"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.Site",
                    ),
                ),
            ],
            options={"verbose_name": "Sitewide alert"},
        )
    ]
