# Generated by Django 2.2.12 on 2020-04-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("utils", "0011_add_short_course_details")]

    operations = [
        migrations.CreateModel(
            name="ResearchType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, max_length=500)),
            ],
        )
    ]
