# Generated by Django 2.2.12 on 2020-06-19 09:56

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0013_legacysitetag_legacysitetaggedpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shortcoursedetailsnippet",
            name="snippet_type",
        ),
        migrations.RemoveField(
            model_name="shortcoursedetailsnippet",
            name="url",
        ),
        migrations.AddField(
            model_name="shortcoursedetailsnippet",
            name="content",
            field=wagtail.fields.RichTextField(blank=True, max_length=255),
        ),
    ]
