# Generated by Django 2.2.12 on 2020-06-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0013_legacysitetag_legacysitetaggedpage"),
        ("utils", "0011_sitewidealertsetting"),
    ]

    operations = []
