# Generated by Django 2.2.12 on 2020-06-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0013_legacysitetag_legacysitetaggedpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtype",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
