# Generated by Django 2.2.12 on 2020-06-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0014_add_research_type_slug"),
        ("utils", "0014_snippet_rich_text_filed"),
    ]

    operations = []
