# Generated by Django 2.2.12 on 2221-11-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0015_merge_20200622_1033"),
        ("utils", "0011_sitewidealertsetting"),
    ]

    operations = []
