# Generated by Django 2.2.12 on 2020-06-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0014_merge_20200618_1659"),
        ("utils", "0015_merge_20200618_1656"),
    ]

    operations = []
