# Generated by Django 2.2.12 on 2020-06-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0014_snippet_rich_text_filed"),
        ("utils", "0016_merge_20200619_0852"),
    ]

    operations = []
