# Generated by Django 2.2.12 on 2020-11-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0017_taxonomy_additions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sector",
            options={
                "verbose_name": "Innovation RCA sector",
                "verbose_name_plural": "Innovation RCA sectors",
            },
        ),
    ]
