# Generated by Django 2.2.12 on 2020-07-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_merge_20200622_1033'),
        ('utils', '0017_merge_20200619_1114'),
    ]

    operations = [
    ]
