# Generated by Django 2.2.12 on 2020-08-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0016_merge_22211127_0750"),
        ("utils", "0018_merge_20200713_1249"),
    ]

    operations = []
