# Generated by Django 3.1.10 on 2021-07-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0019_update_contact_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TapWidgetSnippet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("script_code", models.TextField(blank=True)),
                (
                    "admin_title",
                    models.CharField(
                        help_text="The title value is only used to identify the snippet in the admin interface ",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
