# Generated by Django 2.2.12 on 2020-09-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0017_taxonomy_additions"),
        ("utils", "0019_merge_20200811_1514"),
    ]

    operations = []
