# Generated by Django 3.1.10 on 2021-07-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("utils", "0020_add_tap_widget_snippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitewideTapSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_carousels",
                    models.BooleanField(
                        default=False,
                        help_text="Checking this will show the site-wide TAP carousels",
                    ),
                ),
                (
                    "show_widgets",
                    models.BooleanField(
                        default=False,
                        help_text="Checking this will show the site-wide TAP widgets",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitewide TAP settings",
            },
        ),
    ]
