# Generated by Django 2.2.12 on 2020-11-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0018_name_updates"),
        ("utils", "0020_merge_20200930_1023"),
    ]

    operations = []
