# Generated by Django 2.2.12 on 2020-10-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0020_merge_20200930_1023"),
        ("utils", "0017_auto_20201027_1027"),
    ]

    operations = []
