# Generated by Django 2.2.12 on 2021-02-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0019_update_contact_fields"),
        ("utils", "0021_merge_20201103_1636"),
    ]

    operations = []
