# Generated by Django 3.2.14 on 2022-07-13 16:58

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0022_alter_sluggedtaxonomy_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calltoactionsnippet",
            name="link",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("url", wagtail.blocks.URLBlock()),
                                ("title", wagtail.blocks.CharBlock()),
                            ],
                            icon="link",
                        ),
                    ),
                    (
                        "internal_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                ("title", wagtail.blocks.CharBlock(required=False)),
                            ],
                            icon="link",
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
