# Generated by Django 3.2.16 on 2022-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0023_wagtail_3_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacysitetag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
    ]
