# Generated by Django 3.2.16 on 2023-11-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0025_add_cookie_snippet_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediasettings",
            name="pinterest",
            field=models.CharField(
                blank=True,
                default="royalcollegeofart",
                help_text="Your Pinterest handle without the @, e.g. royalcollegeofart",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="socialmediasettings",
            name="tiktok",
            field=models.CharField(
                blank=True,
                default="royalcollegeofart",
                help_text="Your TikTok handle without the @, e.g. royalcollegeofart",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="socialmediasettings",
            name="wechat_url",
            field=models.URLField(
                blank=True,
                default="https://weixin.qq.com/r/uROQiFHEEwxsrRXr90ar",
                help_text="Your full WeChat page url.",
            ),
        ),
    ]
