# Generated by Django 4.2.20 on 2025-07-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0026_add_pinterest_wechat_tiktok_to_socialmediasettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediasettings",
            name="little_red_book_handle",
            field=models.CharField(
                blank=True,
                help_text="Your Little Red Book handle without the @, e.g. royalcollegeofart",
                max_length=255,
            ),
        ),
    ]
