# Generated by Django 5.2.11 on 2026-04-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0027_add_little_red_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sluggedtaxonomy",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="sluggedtaxonomy",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
