# Generated by Django 3.1.10 on 2021-07-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdetailpage",
            name="asset_heading",
            field=models.CharField(blank=True, max_length=40, verbose_name="Heading"),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="asset_link",
            field=models.URLField(blank=True, max_length=255, verbose_name="Link URL"),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="asset_link_text",
            field=models.CharField(blank=True, max_length=40, verbose_name="Link Text"),
        ),
    ]
