# Generated by Django 3.1.10 on 2021-07-15 14:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20210713_1218"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSeries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("introduction", models.TextField()),
            ],
            options={"ordering": ["title"],},
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
            ],
            options={"ordering": ["title"],},
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="partners",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "partner",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.core.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.core.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.core.blocks.PageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="partners_heading",
            field=models.CharField(blank=True, max_length=120, verbose_name="Heading"),
        ),
        migrations.AlterField(
            model_name="eventdetailpage",
            name="introduction",
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="event_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventtype",
            ),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventseries",
            ),
        ),
    ]
