# Generated by Django 3.1.10 on 2021-07-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_auto_20210716_0924"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventEligibility",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="eligibility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventeligibility",
            ),
        ),
    ]
