# Generated by Django 3.1.10 on 2021-07-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0008_eventdetailpagerelateddirectorate_eventdetailpagerelatedresearchcentre_eventdetailpagerelatedschool",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
            ],
            options={
                "ordering": ["title"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
            ],
            options={
                "ordering": ["title"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="event_cost",
            field=models.CharField(blank=True, max_length=50, verbose_name="Cost"),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="manual_registration_url",
            field=models.URLField(
                blank=True, max_length=255, verbose_name="Booking URL"
            ),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="manual_registration_url_link_text",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Booking URL link text"
            ),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="show_booking_bar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="availability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventavailability",
            ),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventlocation",
            ),
        ),
    ]
