# Generated by Django 3.1.10 on 2021-08-04 10:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_add_intro_and_related_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdetailpagerelatedschool", name="school",
        ),
        migrations.RemoveField(
            model_name="eventdetailpagerelatedschool", name="source_page",
        ),
        migrations.AlterField(
            model_name="eventdetailpagerelateddirectorate",
            name="source_page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_directorates",
                to="events.eventdetailpage",
            ),
        ),
        migrations.DeleteModel(name="EventDetailPageRelatedResearchCentre",),
        migrations.DeleteModel(name="EventDetailPageRelatedSchool",),
    ]
