# Generated by Django 3.1.10 on 2021-08-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_correct_related_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventseries",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
