# Generated by Django 3.1.10 on 2021-08-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_eventdetailpagerelatedpages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdetailpage",
            name="end_date",
            field=models.DateTimeField(
                help_text="Enter the end date of the event. This will be the same as the start date for single day events."
            ),
        ),
        migrations.AlterField(
            model_name="eventdetailpage",
            name="start_date",
            field=models.DateTimeField(help_text="Enter the start date of the event."),
        ),
    ]
