# Generated by Django 3.2.11 on 2022-01-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_convert_event_date_to_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdetailpage",
            name="end_time",
            field=models.TimeField(
                blank=True, help_text="Enter the end time of the event.", null=True
            ),
        ),
        migrations.AddField(
            model_name="eventdetailpage",
            name="start_time",
            field=models.TimeField(
                blank=True, help_text="Enter the start time of the event.", null=True
            ),
        ),
    ]
