# Generated by Django 3.2.11 on 2022-01-25 12:33

import json

from dateutil import parser
from django.db import migrations


def convert_page_datetime_to_date_and_time(page):
    page.start_time = page.start_date.time()
    page.end_time = page.end_date.time()
    page.save()


def convert_revision_datetime_to_date_and_time(revision):
    data = json.loads(revision.content_json)

    start_date = parser.parse(data["start_date"])
    start_time = start_date.time()
    data["start_date"] = start_date.date().isoformat()
    data["start_time"] = start_time.isoformat()

    end_date = parser.parse(data["end_date"])
    end_time = end_date.time()
    data["end_date"] = end_date.date().isoformat()
    data["end_time"] = end_time.isoformat()

    revision.content_json = json.dumps(data)
    revision.save()


def process(apps, page_func, revision_func):
    PageRevision = apps.get_model("wagtailcore", "PageRevision")
    EventDetailPage = apps.get_model("events", "EventDetailPage")

    pages = EventDetailPage.objects.all()

    for page in pages:
        page_func(page)

        for revision in PageRevision.objects.filter(page=page):
            revision_func(revision)


def migrate_datetimes_to_separate_date_and_time(apps, _):
    process(
        apps,
        convert_page_datetime_to_date_and_time,
        convert_revision_datetime_to_date_and_time,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_auto_20220125_1226"),
    ]

    operations = [
        migrations.RunPython(migrate_datetimes_to_separate_date_and_time),
    ]
