# Generated by Django 3.2.11 on 2022-01-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_migrate_event_dates_to_date_and_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdetailpage",
            name="end_date",
            field=models.DateField(
                help_text="Enter the end date of the event. This will be the same as the start date for single day events."
            ),
        ),
        migrations.AlterField(
            model_name="eventdetailpage",
            name="start_date",
            field=models.DateField(help_text="Enter the start date of the event."),
        ),
    ]
