# Generated by Django 3.2.11 on 2022-05-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_alter_eventdetailpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdetailpage",
            name="eligibility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventeligibility",
            ),
        ),
        migrations.AlterField(
            model_name="eventdetailpage",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventlocation",
            ),
        ),
    ]
