# Generated by Django 4.2.17 on 2025-04-21 12:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


def migrate_event_type_to_event_types(apps, schema_editor):
    EventDetailPage = apps.get_model("events", "EventDetailPage")
    EventDetailPageEventType = apps.get_model("events", "EventDetailPageEventType")

    event_detail_page_event_types = []
    for event_detail_page in EventDetailPage.objects.exclude(event_type=None):
        event_detail_page_event_types.append(
            EventDetailPageEventType(
                event_type=event_detail_page.event_type,
                source_page=event_detail_page,
            )
        )

    EventDetailPageEventType.objects.bulk_create(event_detail_page_event_types)


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_link_block_url_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDetailPageEventType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventtype",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_types",
                        to="events.eventdetailpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.RunPython(migrate_event_type_to_event_types, reverse_code=migrations.RunPython.noop),
    ]
