# Generated by Django 4.2.17 on 2025-04-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_eventdetailpageeventtype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdetailpage",
            name="event_type",
        ),
    ]
