# Generated by Django 4.2.20 on 2025-09-19 00:26

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_remove_eventdetailpage_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdetailpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("image", 0),
                    ("heading", 1),
                    ("paragraph", 2),
                    ("quote", 5),
                    ("embed", 6),
                    ("livestream_video", 10),
                    ("cta_link", 14),
                ],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/heading_block.html",
                        },
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "help_text": "Enter quote text only, there is no need to add quotation marks",
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 3), ("author", 4), ("job_title", 4)]],
                        {},
                    ),
                    6: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title to identify the video. Not shown on the page.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "The URL of the video to show.",
                            "label": "Video URL",
                            "max_length": 1000,
                        },
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "The poster image to show as a placeholder for the video. For best results use an image 1920x1080 pixels"
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("video_url", 8), ("poster_image", 9)]],
                        {},
                    ),
                    11: (
                        "rca.navigation.models.URLOrRelativeURLBLock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    12: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title, required if using a URL",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 11), ("page", 12), ("title", 13)]],
                        {},
                    ),
                },
            ),
        ),
    ]
