# Generated by Django 3.1.10 on 2021-07-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationformpage",
            name="form_id",
            field=models.CharField(
                default="",
                help_text="The long number in brackets from the generated JavaScript snippet",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
