# Generated by Django 4.2.20 on 2025-09-19 00:26

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("donate", "0006_decorative_option_image_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationformpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("anchor_heading", 0),
                    ("heading", 1),
                    ("paragraph", 2),
                    ("image", 6),
                    ("quote", 8),
                    ("embed", 9),
                    ("livestream_video", 13),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/anchor_heading_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/heading_block.html",
                        },
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Toggle to make image decorative so they can be ignored by assistive technologies.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("caption", 4), ("decorative", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "help_text": "Enter quote text only, there is no need to add quotation marks",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 7), ("author", 4), ("job_title", 4)]],
                        {},
                    ),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Add a URL from these providers: YouTube, Vimeo, SoundCloud, Twitter.",
                            "label": "Embed media",
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title to identify the video. Not shown on the page.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "The URL of the video to show.",
                            "label": "Video URL",
                            "max_length": 1000,
                        },
                    ),
                    12: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "The poster image to show as a placeholder for the video. For best results use an image 1920x1080 pixels"
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 10), ("video_url", 11), ("poster_image", 12)]],
                        {},
                    ),
                },
            ),
        ),
    ]
