# Generated by Django 3.1.14 on 2021-12-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0006_adds_key_details_field"),
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("images", "0003_extends_image_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipsListingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title used when this page appears in listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.",
                        max_length=255,
                    ),
                ),
                (
                    "contact_model_title",
                    models.CharField(
                        blank=True,
                        help_text="Maximum length of 120 characters",
                        max_length=120,
                        verbose_name="Contact title",
                    ),
                ),
                (
                    "contact_model_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact email"
                    ),
                ),
                (
                    "contact_model_url",
                    models.URLField(blank=True, verbose_name="Contact url"),
                ),
                (
                    "contact_model_text",
                    models.CharField(
                        blank=True,
                        help_text="Maximum length of 250 characters",
                        max_length=250,
                        verbose_name="Contact text",
                    ),
                ),
                (
                    "contact_model_link_text",
                    models.CharField(
                        blank=True,
                        help_text="Optional text for the linked url, form or email",
                        max_length=120,
                        verbose_name="Contact link text",
                    ),
                ),
                ("introduction", models.CharField(blank=True, max_length=500)),
                (
                    "contact_model_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="forms.formpage",
                        verbose_name="Contact form",
                    ),
                ),
                (
                    "contact_model_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="Contact image",
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the image you wish to be displayed when this page appears in listings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
