# Generated by Django 3.1.10 on 2021-12-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programmes", "0066_add_intranet_slug_for_imports"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipSnippet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("programme", models.ManyToManyField(to="programmes.ProgrammePage")),
            ],
            options={"abstract": False,},
        ),
    ]
