# Generated by Django 3.1.10 on 2021-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0002_scholarshiplistingpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipFormSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
            options={"abstract": False,},
        ),
    ]
