# Generated by Django 3.1.14 on 2021-12-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0066_add_intranet_slug_for_imports"),
        ("scholarships", "0004_adds_form_configuration_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipEnquiryFormSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("rca_id_number", models.CharField(max_length=100)),
                ("is_read_data_protection_policy", models.BooleanField()),
                ("is_notification_opt_in", models.BooleanField()),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programmes.programmepage",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
