# Generated by Django 3.2.10 on 2021-12-24 15:17

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0006_adds_scholarship_form_submission_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipEnquiryFormSubmissionScholarshipOrderable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scholarships.scholarship",
                    ),
                ),
                (
                    "scholarship_submission",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarship_submission_scholarships",
                        to="scholarships.scholarshipenquiryformsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
