# Generated by Django 3.2.11 on 2022-01-10 11:12

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0008_auto_20220105_1516"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarshipslistingpage",
            name="scholarship_application_steps",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "step",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("heading", wagtail.core.blocks.CharBlock()),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.core.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.core.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "step_snippet",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            "utils.StepSnippet"
                        ),
                    ),
                ],
                blank=True,
                verbose_name="Application Steps",
            ),
        ),
        migrations.AddField(
            model_name="scholarshipslistingpage",
            name="scholarship_listing_sub_title",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Listing Subtitle"
            ),
        ),
        migrations.AddField(
            model_name="scholarshipslistingpage",
            name="scholarship_listing_title",
            field=models.CharField(
                default="", max_length=50, verbose_name="Listing Title"
            ),
            preserve_default=False,
        ),
    ]
