# Generated by Django 3.2.11 on 2022-01-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0022_alter_sluggedtaxonomy_slug"),
        ("scholarships", "0009_auto_20220110_1112"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipEligibilityCriteria",
            fields=[
                (
                    "sluggedtaxonomy_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="utils.sluggedtaxonomy",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
            bases=("utils.sluggedtaxonomy",),
        ),
        migrations.AddField(
            model_name="scholarshipenquiryformsubmission",
            name="eligibility_criteria",
            field=models.ManyToManyField(
                blank=True, to="scholarships.ScholarshipEligibilityCriteria"
            ),
        ),
    ]
