# Generated by Django 4.2.20 on 2025-11-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0011_wagtail_3_upgrade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarshipslistingpage",
            name="lower_body",
        ),
        migrations.AddField(
            model_name="scholarshipslistingpage",
            name="scholarships_listing_background_color",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                help_text="Select the background color for this section",
                max_length=10,
                verbose_name="Background Color",
            ),
        ),
    ]
