# Generated by Django 4.2.23 on 2025-12-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0012_scholarships_listing_background_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scholarship",
            old_name="funding_categories",
            new_name="other_criteria",
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="summary",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
