# Generated by Django 4.2.27 on 2026-03-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0013_rename_funding_categories_scholarship_other_criteria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarshipenquiryformsubmission",
            name="eligibility_criteria",
        ),
        migrations.RemoveField(
            model_name="scholarshipenquiryformsubmission",
            name="programme",
        ),
        migrations.RemoveField(
            model_name="scholarshipenquiryformsubmissionscholarshiporderable",
            name="scholarship",
        ),
        migrations.RemoveField(
            model_name="scholarshipenquiryformsubmissionscholarshiporderable",
            name="scholarship_submission",
        ),
        migrations.RemoveField(
            model_name="scholarshipslistingpage",
            name="cta_block",
        ),
        migrations.RemoveField(
            model_name="scholarshipslistingpage",
            name="form_introduction",
        ),
        migrations.RemoveField(
            model_name="scholarshipslistingpage",
            name="key_details",
        ),
        migrations.DeleteModel(
            name="ScholarshipEligibilityCriteria",
        ),
        migrations.DeleteModel(
            name="ScholarshipEnquiryFormSubmission",
        ),
        migrations.DeleteModel(
            name="ScholarshipEnquiryFormSubmissionScholarshipOrderable",
        ),
    ]
