# Generated by Django 4.2.27 on 2026-01-28 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0013_rename_funding_categories_scholarship_other_criteria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarshipslistingpage",
            name="cta_block",
        ),
        migrations.RemoveField(
            model_name="scholarshipslistingpage",
            name="form_introduction",
        ),
        migrations.RemoveField(
            model_name="scholarshipslistingpage",
            name="key_details",
        ),
    ]
