# Generated by Django 5.2.11 on 2026-04-01 08:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0013_rename_funding_categories_scholarship_other_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="new_summary",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
