# Generated by Django 5.2.11 on 2026-04-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0015_migrate_summary_to_new_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarship",
            name="summary",
        ),
        migrations.RenameField(
            model_name="scholarship",
            old_name="new_summary",
            new_name="summary",
        ),
    ]
