# Generated by Django 5.2.11 on 2026-04-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scholarships",
            "0016_remove_scholarship_summary_rename_new_summary_scholarship_summary",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
