# Generated by Django 5.2.11 on 2026-04-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0014_remove_scholarship_enquiry_models"),
        ("scholarships", "0017_alter_scholarship_title"),
    ]

    operations = []
