# Generated by Django 5.2.11 on 2026-05-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0018_merge_20260415_0819"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarshipslistingpage",
            name="all_scholarships_disclaimer",
            field=models.TextField(
                default="Browse our full list of funding opportunities. We update this regularly as new awards are confirmed.",
                help_text="Text displayed below 'See all scholarships' heading.",
            ),
            preserve_default=False,
        ),
    ]
