# Generated by Django 5.2.11 on 2026-04-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0018_merge_20260410_0304"),
        ("scholarships", "0018_merge_20260415_0819"),
    ]

    operations = []
