# Generated by Django 5.2.11 on 2026-05-06 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0019_merge_20260416_0214"),
        ("scholarships", "0019_scholarshipslistingpage_all_scholarships_disclaimer"),
    ]

    operations = []
