# Generated by Django 2.2.12 on 2021-02-17 03:26

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('is_citizen', models.CharField(max_length=255)),
                ('programmes', models.CharField(max_length=255)),
                ('courses', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('funding', models.CharField(max_length=255)),
                ('inquiry_reason', models.CharField(max_length=255)),
                ('is_read_data_protection_policy', models.BooleanField()),
                ('is_notification_opt_in', models.BooleanField()),
            ],
        ),
    ]
