# Generated by Django 2.2.12 on 2021-02-17 07:15

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import modelcluster.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('is_citizen', models.BooleanField()),
                ('inquiry_reason', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('is_read_data_protection_policy', models.BooleanField()),
                ('is_notification_opt_in', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionProgrammesOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquire_to_study.Programme')),
                ('submission', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_programmes', to='enquire_to_study.Submission')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionFundingsOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquire_to_study.Funding')),
                ('submission', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_funding', to='enquire_to_study.Submission')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionCoursesOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquire_to_study.Course')),
                ('submission', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_courses', to='enquire_to_study.Submission')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
