# Generated by Django 2.2.12 on 2021-02-18 07:14

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import modelcluster.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('enquire_to_study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryFormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('is_citizen', models.BooleanField()),
                ('is_read_data_protection_policy', models.BooleanField()),
                ('is_notification_opt_in', models.BooleanField()),
                ('inquiry_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='enquire_to_study.InquiryReason')),
                ('start_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='enquire_to_study.StartDate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='submissionfundingsorderable',
            name='submission',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_funding', to='enquire_to_study.EnquiryFormSubmission'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
