# Generated by Django 2.2.12 on 2021-03-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquire_to_study", "0004_enquiretostudysettings"),
        ("enquire_to_study", "0004_remove_funding"),
    ]

    operations = []
