# Generated by Django 2.2.12 on 2021-03-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquire_to_study", "0004_enquiryformkeydetails"),
        ("enquire_to_study", "0005_merge_20210311_1638"),
    ]

    operations = []
