# Generated by Django 2.2.12 on 2021-03-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquire_to_study", "0005_replace_county_of_citizenship"),
    ]

    operations = [
        migrations.AddField(
            model_name="startdate",
            name="qs_code",
            field=models.CharField(
                blank=True,
                help_text="This value needs to match the value of 'code' in the QS Intake item, E.G jan-18",
                max_length=500,
                null=True,
            ),
        ),
    ]
