# Generated by Django 2.2.12 on 2021-03-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquire_to_study", "0006_add_qs_code"),
        ("enquire_to_study", "0006_merge_20210312_1111"),
    ]

    operations = []
