# Generated by Django 2.2.12 on 2021-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquire_to_study", "0008_add_submission_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="startdate",
            name="mailchimp_label",
            field=models.CharField(
                blank=True,
                help_text="This value needs to match the options specified in the 'Intended year of study' field within mailchimps sign-up form , E.G 2021/22",
                max_length=255,
                null=True,
            ),
        ),
    ]
