# Generated by Django 3.2.14 on 2023-02-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquire_to_study', '0010_delete_enquiryformsubmissionprogrammetypesorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryformsubmission',
            name='enquiry_questions',
            field=models.TextField(help_text="Include any questions you'd like to ask here.", null=True),
        ),
    ]
