# Generated by Django 3.2.14 on 2023-03-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquire_to_study', '0010_delete_enquiryformsubmissionprogrammetypesorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryformsubmission',
            name='enquiry_questions',
            field=models.TextField(blank=True, help_text='If you have a specific enquiry or question, please include it here.', max_length=1000, null=True),
        ),
    ]
