# Generated by Django 3.2.21 on 2023-11-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquire_to_study", "0011_add_enquiry_questions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enquiretostudysettings",
            options={"verbose_name": "Register your interest settings"},
        ),
    ]
