# Generated by Django 4.2.14 on 2024-08-06 10:13

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("enquire_to_study", "0013_enquiretostudysettings_intro_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiretostudysettings",
            name="intro_heading",
            field=models.CharField(default="Register your interest", max_length=120),
        ),
        migrations.AddField(
            model_name="enquiretostudysettings",
            name="thank_you_heading",
            field=models.CharField(
                default="Thank you for your enquiry. We're excited that you're thinking of joining us.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="enquiretostudysettings",
            name="thank_you_text",
            field=wagtail.fields.RichTextField(
                default="<p>Your enquiry has been passed to the relevant team and we'll be in touch soon with more information about your programme(s) of interest.</p>"
            ),
        ),
    ]
