# Generated by Django 4.2.17 on 2025-03-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquire_to_study", "0014_enquiretostudysettings_intro_heading_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startdate",
            name="mailchimp_label",
        ),
    ]
