# Generated by Django 5.2.17 on 2026-08-26 08:36

import django.db.models.deletion
from django.db import migrations, models

def forward(apps, schema_editor):
    EnquiryFormSubmissionProgrammesOrderable = apps.get_model(
        "enquire_to_study", "EnquiryFormSubmissionProgrammesOrderable"
    )
    DegreeLevel = apps.get_model("programmes", "DegreeLevel")

    for submission_programme in EnquiryFormSubmissionProgrammesOrderable.objects.all():
        if degree_level := submission_programme.programme.degree_level:
            submission_programme.degree_level = degree_level
            submission_programme.save(update_fields=["degree_level"])


class Migration(migrations.Migration):

    dependencies = [
        ("enquire_to_study", "0015_remove_mailchimp_integration"),
        ("programmes", "0105_programmepagedegreelevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiryformsubmissionprogrammesorderable",
            name="degree_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="programmes.degreelevel",
            ),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
