# Generated by Django 5.2.17 on 2026-08-26 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquire_to_study", "0015_remove_mailchimp_integration"),
        ("programmes", "0106_populate_programmepagedegreelevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiryformsubmissionprogrammesorderable",
            name="degree_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="programmes.degreelevel",
            ),
        ),
    ]
