# Generated by Django 5.2.17 on 2026-08-27 03:31

from django.db import migrations


def forward(apps, schema_editor):
    EnquiryFormSubmissionProgrammesOrderable = apps.get_model(
        "enquire_to_study", "EnquiryFormSubmissionProgrammesOrderable"
    )
    DegreeLevel = apps.get_model("programmes", "DegreeLevel")

    for submission_programme in EnquiryFormSubmissionProgrammesOrderable.objects.all():
        if degree_level := submission_programme.programme.degree_level:
            submission_programme.degree_level = degree_level
            submission_programme.save(update_fields=["degree_level"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "enquire_to_study",
            "0016_enquiryformsubmissionprogrammesorderable_degree_level",
        ),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
