# Generated by Django 2.1.7 on 2019-03-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documents", "0002_customdocument_file_size")]

    operations = [
        migrations.AlterModelOptions(
            name="customdocument",
            options={"verbose_name": "document", "verbose_name_plural": "documents"},
        ),
        migrations.AddField(
            model_name="customdocument",
            name="file_hash",
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
    ]
