# Generated by Django 2.2.12 on 2021-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_customdocument_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdocument',
            name='file',
            field=models.FileField(help_text='Maximum filesize: 10MB.', upload_to='documents', verbose_name='file'),
        ),
    ]
