# Generated by Django 4.2.17 on 2025-01-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_amend_document_helptext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdocument",
            name="file_size",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
