# Generated by Django 2.2.12 on 2020-04-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0002_fields_and_related_models")]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="video_caption",
            field=models.CharField(
                blank=True,
                help_text="The text displayed next to the video play button",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="projectpagesubjectplacement",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="programmes.Subject",
            ),
            preserve_default=False,
        ),
    ]
