# Generated by Django 2.2.12 on 2020-04-22 11:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0012_research_type_taxonomy"),
        ("projects", "0005_add_specific_title_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPageResearchTypePlacement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_types",
                        to="projects.ProjectPage",
                    ),
                ),
                (
                    "research_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="utils.ResearchType",
                    ),
                ),
            ],
        )
    ]
