# Generated by Django 2.2.12 on 2020-04-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_projectpagerelatedresearchpage_projectpagerelatedschoolpage")
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpageprojectleadstaff",
            name="description",
            field=models.TextField(
                blank=True, help_text="Not displayed for small teaser profiles"
            ),
        ),
        migrations.AlterField(
            model_name="projectpagerelatedstaff",
            name="description",
            field=models.TextField(
                blank=True, help_text="Not displayed for small teaser profiles"
            ),
        ),
    ]
