# Generated by Django 2.2.12 on 2020-04-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0008_add_teaser_help_text")]

    operations = [
        migrations.AddField(
            model_name="projectpickerpage",
            name="featured_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_project",
                to="projects.ProjectPage",
            ),
        ),
        migrations.AddField(
            model_name="projectpickerpage",
            name="introduction",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
