# Generated by Django 2.2.12 on 2020-06-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0010_improve_relationships_between_models")]

    operations = [
        migrations.AlterField(
            model_name="relatedprojectpage",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.ProjectPage"
            ),
        )
    ]
