# Generated by Django 2.2.12 on 2020-06-10 15:54

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_fix_page_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="external_links",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                ("url", wagtail.core.blocks.URLBlock(required=False)),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="External Links",
            ),
        ),
    ]
