# Generated by Django 2.2.12 on 2020-06-11 09:55

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0007_staffrole"),
        ("projects", "0012_projectpage_external_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPageExpertisePlacement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_of_expertise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="people.AreaOfExpertise",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertise",
                        to="projects.ProjectPage",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProjectPageSubjectPlacement",
        ),
    ]
