# Generated by Django 2.2.12 on 2020-06-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_create_expertise_placement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectpageresearchtypeplacement",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="projectpageresearchtypeplacement",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
