# Generated by Django 2.2.12 on 2020-06-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_init_taxonomy_slugs"),
        ("projects", "0015_field_label_updates"),
    ]

    operations = []
