# Generated by Django 2.2.12 on 2020-08-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_merge_20200622_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpageprojectleadstaff",
            name="first_name",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name="projectpageprojectleadstaff",
            name="surname",
            field=models.CharField(blank=-1, max_length=125),
        ),
        migrations.AlterField(
            model_name="projectpagerelatedstaff",
            name="first_name",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name="projectpagerelatedstaff",
            name="surname",
            field=models.CharField(blank=-1, max_length=125),
        ),
    ]
