# Generated by Django 2.2.12 on 2020-08-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_allow_blank_values"),
        ("projects", "0017_merge_20200713_1249"),
    ]

    operations = []
