# Generated by Django 2.2.12 on 2020-09-30 09:08

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0017_taxonomy_additions"),
        ("projects", "0017_allow_blank_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPageSectorPlacement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_sectors",
                        to="projects.ProjectPage",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="utils.Sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectPageResearchThemePlacement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_research_themes",
                        to="projects.ProjectPage",
                    ),
                ),
                (
                    "research_theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="utils.ResearchTheme",
                    ),
                ),
            ],
        ),
    ]
