# Generated by Django 2.2.12 on 2021-01-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0018_projectpageresearchthemeplacement_projectpagesectorplacement",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpagerelatedresearchpage",
            name="page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AlterField(
            model_name="projectpagerelatedschoolpage",
            name="page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
    ]
