# Generated by Django 2.2.12 on 2020-09-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_merge_20200803_2053"),
        (
            "projects",
            "0018_projectpageresearchthemeplacement_projectpagesectorplacement",
        ),
    ]

    operations = []
