# Generated by Django 2.2.12 on 2020-11-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0018_projectpageresearchthemeplacement_projectpagesectorplacement",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="specification_document_link_text",
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                verbose_name="Project PDF link text",
            ),
        ),
    ]
