# Generated by Django 2.2.12 on 2021-02-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_add_pdf_link_text_help"),
        ("projects", "0022_merge_20210210_0850"),
    ]

    operations = []
