# Generated by Django 2.2.19 on 2021-04-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_merge_20210212_1510"),
    ]

    operations = [
        migrations.RemoveField(model_name="projectpage", name="hero_colour_option",),
    ]
