# Generated by Django 3.1.7 on 2021-04-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_merge_20210212_1510"),
        ("projects", "0024_remove_hero_colour_options"),
    ]

    operations = []
