# Generated by Django 3.2.11 on 2022-02-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_add_contact_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="specification_document_link_text",
            field=models.CharField(
                blank=True,
                help_text="You must enter link text if you add a Project PDF, e.g. 'Download project PDF'",
                max_length=300,
                null=True,
                verbose_name="Project PDF link text",
            ),
        ),
    ]
