# Generated by Django 3.2.14 on 2023-02-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_adds_collaborator_fields'),
        ('projects', '0028_wagtail_3_upgrade'),
    ]

    operations = [
    ]
