# Generated by Django 3.2.16 on 2023-02-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_merge_20221103_1504'),
        ('projects', '0029_merge_20230227_0214'),
    ]

    operations = [
    ]
