# Generated by Django 3.2.16 on 2023-09-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_add_embed_to_richtext_in_projectpage_more_information'),
        ('projects', '0030_use_json_field'),
    ]

    operations = [
    ]
