# Generated by Django 3.2.16 on 2023-05-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_merge_20230227_0350'),
        ('projects', '0030_use_json_field'),
    ]

    operations = [
    ]
