# Generated by Django 3.2.16 on 2023-08-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_add_embed_to_richtext_in_projectpage_more_information"),
        ("projects", "0031_merge_0030_merge_20230227_0350_0030_use_json_field"),
    ]

    operations = []
