# Generated by Django 4.2.11 on 2024-05-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_required_title_and_play_button_label_gallery_block"),
        ("projects", "0033_merge_20231024_0708"),
    ]

    operations = []
