# Generated by Django 2.2.4 on 2019-08-21 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_customimage_file_hash"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="call_to_action"),
        migrations.AddField(
            model_name="homepage",
            name="hero_colour_option",
            field=models.CharField(
                choices=[
                    ("1", "Light text on a dark image"),
                    ("2", "Dark text on a light image"),
                ],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_sub_text",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_text",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strapline_cta_text",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strapline_cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strapline",
            field=models.CharField(max_length=125),
        ),
    ]
