# Generated by Django 2.2.4 on 2019-08-23 13:22

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_customimage_file_hash"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="call_to_action"),
        migrations.AddField(
            model_name="homepage",
            name="hero_colour_option",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Light text on dark image"),
                    (2, "dark text on light image"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_sub_text",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_text",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strapline_cta_text",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strapline_cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strapline",
            field=models.CharField(max_length=125),
        ),
        migrations.CreateModel(
            name="HomePageTransofmrationBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Large heading displayed above the image",
                        max_length=125,
                    ),
                ),
                ("video", models.URLField(blank=True)),
                (
                    "video_caption",
                    models.CharField(
                        blank=True,
                        help_text="The text dipsplayed next to the video play button",
                        max_length=80,
                    ),
                ),
                (
                    "sub_heading",
                    models.CharField(
                        blank=True,
                        help_text="The title below the image",
                        max_length=125,
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        blank=True,
                        help_text="A title for the linked related page",
                        max_length=125,
                    ),
                ),
                (
                    "page_summary",
                    models.CharField(
                        blank=True,
                        help_text="A summary for the linked related page",
                        max_length=250,
                    ),
                ),
                (
                    "page_link_url",
                    models.URLField(blank=True, help_text="A url to a related page"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformation_blocks",
                        to="home.HomePage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomePageStatsBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                (
                    "statistics",
                    wagtail.fields.StreamField(
                        [
                            (
                                "statistic",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "summary",
                                            wagtail.blocks.CharBlock(
                                                help_text="E.g.  1 in 3 of our graduates are business owners or independent professionals",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "before",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "after",
                                            wagtail.blocks.CharBlock(
                                                help_text="E.g. '%'",
                                                max_length=2,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "number",
                                            wagtail.blocks.IntegerBlock(
                                                help_text="E.g. '33'", required=False
                                            ),
                                        ),
                                        (
                                            "meta",
                                            wagtail.blocks.CharBlock(
                                                help_text="Small title below the number, e.g 'Nationalities'",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats_block",
                        to="home.HomePage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomePagePartnershipBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                ("summary", models.CharField(max_length=250)),
                (
                    "slides",
                    wagtail.fields.StreamField(
                        [
                            (
                                "slide",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "type",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "summary",
                                            wagtail.blocks.TextBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships_block",
                        to="home.HomePage",
                    ),
                ),
            ],
        ),
    ]
