# Generated by Django 2.2.4 on 2019-08-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0003_homepage_blocks_and_fields")]

    operations = [
        migrations.RemoveField(model_name="homepage", name="hero_colour_option")
    ]
