# Generated by Django 2.2.4 on 2019-08-22 22:17

import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_customimage_file_hash"),
        ("home", "0005_partnerships_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageStatsBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                (
                    "statistics",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "statistic",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.core.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "summary",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="E.g,  1 in 3 of our graduates are business owners or independent professionals",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "after",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="E.g, '%'",
                                                max_length=2,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "number",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="E.g, '33'",
                                                max_length=5,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "meta",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Small title below the number E.g, 'Nationalities'",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats_block",
                        to="home.HomePage",
                    ),
                ),
            ],
        )
    ]
