# Generated by Django 2.2.4 on 2019-08-28 15:27

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0005_add_hero_color_option_integer")]

    operations = [
        migrations.AlterField(
            model_name="homepagepartnershipblock",
            name="slides",
            field=wagtail.fields.StreamField(
                [
                    (
                        "slide",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("type", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "summary",
                                    wagtail.blocks.TextBlock(required=False),
                                ),
                                ("link", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    )
                ]
            ),
        )
    ]
