# Generated by Django 2.2.12 on 2020-10-28 20:37

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_add_hero_image_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagepartnershipblock",
            name="slides",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "Page",
                        wagtail.core.blocks.StreamBlock(
                            [
                                ("page", wagtail.core.blocks.PageChooserBlock()),
                                (
                                    "custom_teaser",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.core.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "meta",
                                                wagtail.core.blocks.CharBlock(
                                                    help_text="Small tag value displayed below the title",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "text",
                                                wagtail.core.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(),
                                            ),
                                            (
                                                "link",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.core.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.core.blocks.URLBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ]
            ),
        ),
    ]
