# Generated by Django 3.1.10 on 2021-09-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_add_tap_widget"),
        ("home", "0009_add_settings_to_control_content_fetch"),
    ]

    operations = []
