# Generated by Django 3.1.10 on 2021-10-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_merge_20210910_1128"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagetransofmrationblock",
            name="page_title",
            field=models.CharField(
                blank=True,
                help_text="Please add informative help text that includes the name or nature of the target content",
                max_length=125,
            ),
        ),
        migrations.AlterField(
            model_name="homepagetransofmrationblock",
            name="video_caption",
            field=models.CharField(
                blank=True,
                help_text="The text displayed next to the video play button",
                max_length=80,
            ),
        ),
    ]
