# Generated by Django 3.1.10 on 2021-09-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_merge_20210910_1128"),
        ("home", "0010_merge_20210826_0929"),
    ]

    operations = []
