# Generated by Django 3.1.10 on 2021-10-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_update_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagetransofmrationblock",
            name="read_more_link_text",
            field=models.CharField(
                blank=True,
                help_text="Specific text to use for the 'read more' link",
                max_length=125,
            ),
        ),
    ]
