# Generated by Django 3.1.10 on 2021-10-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_update_help_text"),
        ("home", "0011_merge_20210927_1519"),
    ]

    operations = []
