# Generated by Django 3.1.10 on 2021-10-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_add_read_more_text"),
        ("home", "0012_merge_20211019_1545"),
    ]

    operations = []
