# Generated by Django 3.2.14 on 2022-07-13 16:58

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_add_read_more_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagepartnershipblock",
            name="slides",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Page",
                        wagtail.blocks.StreamBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "custom_teaser",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "meta",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Small tag value displayed below the title",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.blocks.URLBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepagestatsblock",
            name="statistics",
            field=wagtail.fields.StreamField(
                [
                    (
                        "statistic",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "summary",
                                    wagtail.blocks.CharBlock(
                                        help_text="E.g.  1 in 3 of our graduates are business owners or independent professionals",
                                        required=False,
                                    ),
                                ),
                                ("before", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "after",
                                    wagtail.blocks.CharBlock(
                                        help_text="E.g. '%'",
                                        max_length=2,
                                        required=False,
                                    ),
                                ),
                                (
                                    "number",
                                    wagtail.blocks.IntegerBlock(
                                        help_text="E.g. '33'", required=False
                                    ),
                                ),
                                (
                                    "meta",
                                    wagtail.blocks.CharBlock(
                                        help_text="Small title below the number, e.g 'Nationalities'",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
