# Generated by Django 3.2.12 on 2022-07-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_adds_news_events_link_fields"),
        ("home", "0013_merge_20211023_1908"),
    ]

    operations = []
