# Generated by Django 3.2.14 on 2023-02-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_adds_news_events_link_fields'),
        ('home', '0013_wagtail_3_upgrade'),
    ]

    operations = [
    ]
