# Generated by Django 3.2.16 on 2023-02-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20230227_0237'),
        ('home', '0015_merge_0013_wagtail_3_upgrade_0014_merge_20220712_0957'),
    ]

    operations = [
    ]
