# Generated by Django 4.2.15 on 2024-08-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_homepagefeaturedalumnistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="use_api_for_alumni_stories",
        ),
    ]
