# Generated by Django 4.2.17 on 2025-04-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_link_block_url_label"),
        ("home", "0017_populate_homepagefeaturedalumnistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="featured_event",
            field=models.ForeignKey(
                blank=True,
                help_text="The featured event to display. If none is selected, this defaults to the next upcoming event. If the selected event's end date is in the past, this defaults to the next upcoming event.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="events.eventdetailpage",
            ),
        ),
    ]
