# Generated by Django 4.2.17 on 2025-07-14 02:08

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_homepage_featured_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("body_section", 23)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("light", "Light"), ("dark", "Dark")],
                            "help_text": "Select the background color for this section",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Enter the strapline title", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Enter the strapline content", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("content", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the transformation title",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Enter the transformation content",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("content", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for featured alumni stories",
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Enter the alumni name", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Enter the alumni story", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 8), ("story", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"help_text": "Add featured alumni stories", "required": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("stories", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Enter the partnerships title", "required": True},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Enter the partnerships content",
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("content", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for news, events and alumni stories",
                            "required": True,
                        },
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Enter the content for news, events and alumni stories",
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("content", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the news and events title",
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Enter the content for news and events",
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("content", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("strapline", 3),
                                ("transformation", 6),
                                ("featured_alumni_stories", 12),
                                ("partnerships", 15),
                                ("news_events_alumni_stories", 18),
                                ("news_events", 21),
                            ]
                        ],
                        {"help_text": "Add content to this section", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("background_color", 0), ("content", 22)]],
                        {"required": True},
                    ),
                },
            ),
        ),
    ]
