# Generated by Django 4.2.17 on 2025-07-15 08:24

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_homepage_featured_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("body_section", 35), ("statistics", 44)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("light", "Light"), ("dark", "Dark")],
                            "help_text": "Select the background color for this section",
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Call to action URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Call to action text", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("cta_url", 2), ("cta_text", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Large heading displayed above the image",
                            "max_length": 125,
                        },
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Select an image", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL to a video", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The text displayed next to the video play button",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title below the image",
                            "max_length": 125,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Please add informative help text that includes the name or nature of the target content",
                            "max_length": 125,
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A summary for the linked related page",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "A url to a related page",
                            "label": "Page link URL",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specific text to use for the 'read more' link",
                            "max_length": 125,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 5),
                                ("image", 6),
                                ("video", 7),
                                ("video_caption", 8),
                                ("sub_heading", 9),
                                ("page_title", 10),
                                ("page_summary", 11),
                                ("page_link_url", 12),
                                ("read_more_link_text", 13),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["editorial.EditorialPage"]},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {
                            "help_text": "Select alumni stories to feature",
                            "required": True,
                        },
                    ),
                    17: ("wagtail.blocks.StructBlock", [[("stories", 16)]], {}),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Enter the partnerships title"},
                    ),
                    19: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Enter a summary for the partnerships section"},
                    ),
                    20: ("wagtail.blocks.PageChooserBlock", (), {}),
                    21: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Small tag value displayed below the title",
                            "required": False,
                        },
                    ),
                    23: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    24: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 21), ("url", 24)]],
                        {"required": False},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 21),
                                ("meta", 22),
                                ("text", 21),
                                ("image", 23),
                                ("link", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [[("page", 20), ("custom_teaser", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 18), ("summary", 19), ("slides", 27)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title to display above the news and events listing",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The text to display for the 'View all news and events' link",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Add a link to view all news and events",
                            "label": "Link target URL",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "The featured event to display. If none is selected, this defaults to the next upcoming event. If the selected event's end date is in the past, this defaults to the next upcoming event.",
                            "page_type": ["events.EventDetailPage"],
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 29),
                                ("link_text", 30),
                                ("link_target_url", 31),
                                ("featured_event", 32),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("strapline", 4),
                                ("transformation", 14),
                                ("featured_alumni_stories", 17),
                                ("partnerships", 28),
                                ("news_events", 33),
                            ]
                        ],
                        {"help_text": "Add content to this section", "required": True},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("background_color", 0), ("content", 34)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Enter the statistics section title"},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "E.g.  1 in 3 of our graduates are business owners or independent professionals",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "E.g. '%'", "max_length": 2, "required": False},
                    ),
                    39: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "E.g. '33'", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Small title below the number, e.g 'Nationalities'",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("summary", 37),
                                ("before", 21),
                                ("after", 38),
                                ("number", 39),
                                ("meta", 40),
                            ]
                        ],
                        {},
                    ),
                    42: ("wagtail.blocks.StreamBlock", [[("statistic", 41)]], {}),
                    43: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Select a background image for the statistics section",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 36), ("statistics", 42), ("background_image", 43)]],
                        {},
                    ),
                },
            ),
        ),
    ]
