# Generated by Django 4.2.17 on 2025-07-16 02:08

from django.db import migrations
import rca.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=rca.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AlterField(
            model_name="homepagepartnershipblock",
            name="slides",
            field=rca.utils.fields.StreamField(block_lookup={}),
        ),
        migrations.AlterField(
            model_name="homepagestatsblock",
            name="statistics",
            field=rca.utils.fields.StreamField(block_lookup={}),
        ),
    ]
