# Generated by Django 4.2.20 on 2025-07-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_use_custom_streamfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagepartnershipblock",
            name="source_page",
        ),
        migrations.RemoveField(
            model_name="homepagestatsblock",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="homepagestatsblock",
            name="source_page",
        ),
        migrations.RemoveField(
            model_name="homepagetransofmrationblock",
            name="image",
        ),
        migrations.RemoveField(
            model_name="homepagetransofmrationblock",
            name="source_page",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="featured_event",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="news_and_events_link_target_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="news_and_events_link_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="news_and_events_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="strapline",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="strapline_cta_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="strapline_cta_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="use_api_for_news_and_events",
        ),
        migrations.DeleteModel(
            name="HomePageFeaturedAlumniStory",
        ),
        migrations.DeleteModel(
            name="HomePagePartnershipBlock",
        ),
        migrations.DeleteModel(
            name="HomePageStatsBlock",
        ),
        migrations.DeleteModel(
            name="HomePageTransofmrationBlock",
        ),
    ]
