# Generated by Django 4.2.23 on 2025-12-18 04:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("images", "0008_wagtail_63_upgrade"),
        (
            "wagtail_personalisation",
            "0026_alter_dayrule_segment_alter_devicerule_segment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActionCallToAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Maximum 40 characters", max_length=40),
                ),
                (
                    "description",
                    models.CharField(help_text="Maximum 65 characters", max_length=65),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        help_text="Link to an external URL (e.g., https://example.com)",
                    ),
                ),
                (
                    "link_label",
                    models.CharField(
                        help_text="Maximum 40 characters for the link button text",
                        max_length=40,
                    ),
                ),
                (
                    "user_action",
                    models.CharField(
                        choices=[
                            ("page_load", "On page load"),
                            ("inactivity", "On inactivity after X seconds"),
                            ("scroll", "On scroll after X% of the way down"),
                            ("exit_intent", "On exit intent"),
                        ],
                        default="page_load",
                        help_text="Choose when this CTA should appear",
                        max_length=20,
                    ),
                ),
                (
                    "inactivity_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of seconds of inactivity before showing the CTA (only for 'On inactivity')",
                        null=True,
                    ),
                ),
                (
                    "scroll_percentage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Percentage of page scrolled before showing the CTA (only for 'On scroll', e.g., 50 for 50%)",
                        null=True,
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when this CTA should start appearing on pages",
                        null=True,
                        verbose_name="Go live date/time",
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when this CTA should stop appearing on pages",
                        null=True,
                        verbose_name="Expiry date/time",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Image to display in the pop-up CTA",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "internal_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to an internal page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Action Pop-up CTA",
                "verbose_name_plural": "User Action Pop-up CTAs",
            },
        ),
        migrations.CreateModel(
            name="UserActionCTASegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="personalisation.useractioncalltoaction",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalised_call_to_actions",
                        to="wagtail_personalisation.segment",
                    ),
                ),
            ],
            options={
                "unique_together": {("segment", "call_to_action")},
            },
        ),
        migrations.CreateModel(
            name="UserActionCTAPageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home.homepage", "Home Page"),
                            ("programmes.programmepage", "Programme Page"),
                            ("programmes.programmeindexpage", "Programme Index Page"),
                            ("events.eventdetailpage", "Event Detail Page"),
                            ("events.eventindexpage", "Event Index Page"),
                            ("editorial.editorialpage", "Editorial Page"),
                            (
                                "editorial.editoriallistingpage",
                                "Editorial Listing Page",
                            ),
                            ("guides.guidepage", "Guide Page"),
                            ("projects.projectpage", "Project Page"),
                            ("research.researchcentrepage", "Research Centre Page"),
                            ("schools.schoolpage", "School Page"),
                            ("people.staffpage", "Staff Page"),
                            ("people.studentpage", "Student Page"),
                            ("people.staffindexpage", "Staff Index Page"),
                            ("people.studentindexpage", "Student Index Page"),
                            ("shortcourses.shortcoursepage", "Short Course Page"),
                            ("landingpages.landingpage", "Landing Page"),
                            ("landingpages.alumnilandingpage", "Alumni Landing Page"),
                            (
                                "landingpages.developmentlandingpage",
                                "Development Landing Page",
                            ),
                            (
                                "landingpages.enterpriselandingpage",
                                "Enterprise Landing Page",
                            ),
                            (
                                "landingpages.innovationlandingpage",
                                "Innovation Landing Page",
                            ),
                            (
                                "landingpages.researchlandingpage",
                                "Research Landing Page",
                            ),
                            ("landingpages.taplandingpage", "Tap Landing Page"),
                            ("landingpages.eelandingpage", "EE Landing Page"),
                            ("standardpages.informationpage", "Information Page"),
                            ("standardpages.indexpage", "Index Page"),
                            ("forms.formpage", "Form Page"),
                            ("donate.donationformpage", "Donation Form Page"),
                            (
                                "scholarships.scholarshipslistingpage",
                                "Scholarships Listing Page",
                            ),
                        ],
                        help_text="Select the page type where this CTA should appear",
                        max_length=100,
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_types",
                        to="personalisation.useractioncalltoaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("page_type", "call_to_action")},
            },
        ),
    ]
