# Generated by Django 4.2.23 on 2026-01-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalisation", "0002_embeddedfootercalltoaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddedfootercalltoaction",
            name="link_label",
            field=models.CharField(
                blank=True,
                help_text="Maximum 40 characters for the link button text. If using an internal link, leave blank to use the page's title.",
                max_length=40,
            ),
        ),
    ]
