# Generated by Django 4.2.23 on 2026-01-07 02:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import rca.utils.fields
import rca.utils.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtail_personalisation",
            "0026_alter_dayrule_segment_alter_devicerule_segment_and_more",
        ),
        ("personalisation", "0003_make_link_label_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollapsibleNavigationCallToAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when this CTA should start appearing.",
                        null=True,
                        verbose_name="Go live date/time",
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when this CTA should stop appearing.",
                        null=True,
                        verbose_name="Expiry date/time",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="This is for internal purposes only.", max_length=255
                    ),
                ),
                ("links", rca.utils.fields.StreamField(block_lookup={})),
            ],
            options={
                "abstract": False,
            },
            bases=(rca.utils.models.StyledPreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CollapsibleNavigationCTASegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="personalisation.collapsiblenavigationcalltoaction",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collapsible_navigation_ctas",
                        to="wagtail_personalisation.segment",
                    ),
                ),
            ],
            options={
                "unique_together": {("segment", "call_to_action")},
            },
        ),
        migrations.CreateModel(
            name="CollapsibleNavigationCTAPageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home.homepage", "Home Page"),
                            ("programmes.programmepage", "Programme Page"),
                            ("programmes.programmeindexpage", "Programme Index Page"),
                            ("events.eventdetailpage", "Event Detail Page"),
                            ("events.eventindexpage", "Event Index Page"),
                            ("editorial.editorialpage", "Editorial Page"),
                            (
                                "editorial.editoriallistingpage",
                                "Editorial Listing Page",
                            ),
                            ("guides.guidepage", "Guide Page"),
                            ("projects.projectpage", "Project Page"),
                            ("projects.projectpickerpage", "Project Picker Page"),
                            ("research.researchcentrepage", "Research Centre Page"),
                            ("schools.schoolpage", "School Page"),
                            ("people.staffpage", "Staff Page"),
                            ("people.studentpage", "Student Page"),
                            ("people.staffindexpage", "Staff Index Page"),
                            ("people.studentindexpage", "Student Index Page"),
                            ("shortcourses.shortcoursepage", "Short Course Page"),
                            ("landingpages.landingpage", "Landing Page"),
                            ("landingpages.alumnilandingpage", "Alumni Landing Page"),
                            (
                                "landingpages.developmentlandingpage",
                                "Development Landing Page",
                            ),
                            (
                                "landingpages.enterpriselandingpage",
                                "Enterprise Landing Page",
                            ),
                            (
                                "landingpages.innovationlandingpage",
                                "Innovation Landing Page",
                            ),
                            (
                                "landingpages.researchlandingpage",
                                "Research Landing Page",
                            ),
                            ("landingpages.taplandingpage", "Tap Landing Page"),
                            ("landingpages.eelandingpage", "EE Landing Page"),
                            ("standardpages.informationpage", "Information Page"),
                            ("standardpages.indexpage", "Index Page"),
                            ("forms.formpage", "Form Page"),
                            ("donate.donationformpage", "Donation Form Page"),
                            (
                                "scholarships.scholarshipslistingpage",
                                "Scholarships Listing Page",
                            ),
                        ],
                        help_text="Select the page type where this CTA should appear",
                        max_length=100,
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_types",
                        to="personalisation.collapsiblenavigationcalltoaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("page_type", "call_to_action")},
            },
        ),
    ]
