# Generated by Django 4.2.23 on 2026-01-06 04:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import rca.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        (
            "wagtail_personalisation",
            "0026_alter_dayrule_segment_alter_devicerule_segment_and_more",
        ),
        ("personalisation", "0003_make_link_label_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCountdownCallToAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when this CTA should start appearing.",
                        null=True,
                        verbose_name="Go live date/time",
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when this CTA should stop appearing.",
                        null=True,
                        verbose_name="Expiry date/time",
                    ),
                ),
                (
                    "user_action",
                    models.CharField(
                        choices=[
                            ("page_load", "On page load"),
                            ("inactivity", "On inactivity after X seconds"),
                            ("scroll", "On scroll after X% of the way down"),
                            ("exit_intent", "On exit intent"),
                        ],
                        default="page_load",
                        help_text="Choose when this CTA should appear",
                        max_length=20,
                    ),
                ),
                (
                    "inactivity_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of seconds of inactivity before showing the CTA (only for 'On inactivity')",
                        null=True,
                    ),
                ),
                (
                    "scroll_percentage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Percentage of page scrolled before showing the CTA (only for 'On scroll', e.g., 50 for 50%)",
                        null=True,
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        help_text="Link to an external URL (e.g., https://example.com)",
                    ),
                ),
                (
                    "link_label",
                    models.CharField(
                        blank=True,
                        help_text="Maximum 40 characters for the link button text. If using an internal link, leave blank to use the page's title.",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("countdown_timer_pre_text", models.CharField(blank=True)),
                (
                    "countdown_to",
                    models.CharField(
                        blank=True,
                        choices=[("start", "Start date"), ("end", "End date")],
                        help_text="Choose which date the countdown must count to",
                        max_length=10,
                    ),
                ),
                (
                    "internal_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to an internal page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Countdown CTA",
                "verbose_name_plural": "Event Countdown CTAs",
            },
            bases=(rca.personalisation.models.StyledPreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EventCountdownCTASegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="personalisation.eventcountdowncalltoaction",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_countdown_ctas",
                        to="wagtail_personalisation.segment",
                    ),
                ),
            ],
            options={
                "unique_together": {("segment", "call_to_action")},
            },
        ),
        migrations.CreateModel(
            name="EventCountdownCTAPageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home.homepage", "Home Page"),
                            ("programmes.programmepage", "Programme Page"),
                            ("programmes.programmeindexpage", "Programme Index Page"),
                            ("events.eventdetailpage", "Event Detail Page"),
                            ("events.eventindexpage", "Event Index Page"),
                            ("editorial.editorialpage", "Editorial Page"),
                            (
                                "editorial.editoriallistingpage",
                                "Editorial Listing Page",
                            ),
                            ("guides.guidepage", "Guide Page"),
                            ("projects.projectpage", "Project Page"),
                            ("projects.projectpickerpage", "Project Picker Page"),
                            ("research.researchcentrepage", "Research Centre Page"),
                            ("schools.schoolpage", "School Page"),
                            ("people.staffpage", "Staff Page"),
                            ("people.studentpage", "Student Page"),
                            ("people.staffindexpage", "Staff Index Page"),
                            ("people.studentindexpage", "Student Index Page"),
                            ("shortcourses.shortcoursepage", "Short Course Page"),
                            ("landingpages.landingpage", "Landing Page"),
                            ("landingpages.alumnilandingpage", "Alumni Landing Page"),
                            (
                                "landingpages.developmentlandingpage",
                                "Development Landing Page",
                            ),
                            (
                                "landingpages.enterpriselandingpage",
                                "Enterprise Landing Page",
                            ),
                            (
                                "landingpages.innovationlandingpage",
                                "Innovation Landing Page",
                            ),
                            (
                                "landingpages.researchlandingpage",
                                "Research Landing Page",
                            ),
                            ("landingpages.taplandingpage", "Tap Landing Page"),
                            ("landingpages.eelandingpage", "EE Landing Page"),
                            ("standardpages.informationpage", "Information Page"),
                            ("standardpages.indexpage", "Index Page"),
                            ("forms.formpage", "Form Page"),
                            ("donate.donationformpage", "Donation Form Page"),
                            (
                                "scholarships.scholarshipslistingpage",
                                "Scholarships Listing Page",
                            ),
                        ],
                        help_text="Select the page type where this CTA should appear",
                        max_length=100,
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_types",
                        to="personalisation.eventcountdowncalltoaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("page_type", "call_to_action")},
            },
        ),
    ]
