# Generated by Django 4.2.23 on 2026-01-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalisation", "0005_collapsiblenavigationcalltoaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collapsiblenavigationcalltoaction",
            name="inactivity_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of seconds of inactivity before showing the CTA (only for 'On inactivity')",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collapsiblenavigationcalltoaction",
            name="scroll_percentage",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Percentage of page scrolled before showing the CTA (only for 'On scroll', e.g., 50 for 50%)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collapsiblenavigationcalltoaction",
            name="user_action",
            field=models.CharField(
                choices=[
                    ("page_load", "On page load"),
                    ("inactivity", "On inactivity after X seconds"),
                    ("scroll", "On scroll after X% of the way down"),
                    ("exit_intent", "On exit intent"),
                ],
                default="page_load",
                help_text="Choose when this CTA should appear",
                max_length=20,
            ),
        ),
    ]
