# Generated by Django 4.2.23 on 2026-01-13 04:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtail_personalisation",
            "0026_alter_dayrule_segment_alter_devicerule_segment_and_more",
        ),
        ("personalisation", "0006_user_actions_for_collapsible_nav"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTypeRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("new", "New user"), ("returning", "Returning user")],
                        default="new",
                        help_text="Select whether to target new or returning users",
                        max_length=20,
                    ),
                ),
                (
                    "segment",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="wagtail_personalisation.segment",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Type Rule",
            },
        ),
    ]
