# Generated by Django 4.2.23 on 2026-01-12 02:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("personalisation", "0006_user_actions_for_collapsible_nav"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActionCTAPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "include_children",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the CTA will also appear on all child pages of the selected page",
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="personalisation.useractioncalltoaction",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Select the specific page where this CTA should appear",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "call_to_action")},
            },
        ),
        migrations.CreateModel(
            name="EventCountdownCTAPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "include_children",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the CTA will also appear on all child pages of the selected page",
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="personalisation.eventcountdowncalltoaction",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Select the specific page where this CTA should appear",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "call_to_action")},
            },
        ),
        migrations.CreateModel(
            name="EmbeddedFooterCTAPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "include_children",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the CTA will also appear on all child pages of the selected page",
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="personalisation.embeddedfootercalltoaction",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Select the specific page where this CTA should appear",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "call_to_action")},
            },
        ),
        migrations.CreateModel(
            name="CollapsibleNavigationCTAPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "include_children",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the CTA will also appear on all child pages of the selected page",
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="personalisation.collapsiblenavigationcalltoaction",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Select the specific page where this CTA should appear",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "call_to_action")},
            },
        ),
    ]
