# Generated by Django 4.2.27 on 2026-01-23 02:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtail_personalisation",
            "0026_alter_dayrule_segment_alter_devicerule_segment_and_more",
        ),
        ("personalisation", "0009_sort_page_type_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginContinentRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("AF", "Africa"),
                            ("AN", "Antarctica"),
                            ("AS", "Asia"),
                            ("EU", "Europe"),
                            ("NA", "North America"),
                            ("OC", "Oceania"),
                            ("SA", "South America"),
                        ],
                        help_text="Select origin continent of the request that this rule will match against. This rule uses Cloudflare's IP geolocation to detect the user's continent, with fallback to country-based detection.",
                        max_length=2,
                    ),
                ),
                (
                    "segment",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="wagtail_personalisation.segment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Origin Continent Rule",
            },
        ),
    ]
