# Generated by Django 4.2.27 on 2026-01-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personalisation", "0010_origincontinentrule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="origincontinentrule",
            options={"verbose_name": "Origin continent Rule"},
        ),
        migrations.AlterModelOptions(
            name="usertyperule",
            options={"verbose_name": "User type Rule"},
        ),
    ]
