# Generated by Django 5.2.17 on 2026-10-06 02:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalisation", "0011_update_verbose_name_for_consistency"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollapsibleNavigationCTAExcludedPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "include_children",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the CTA will also be excluded from all child pages of the selected page",
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_pages",
                        to="personalisation.collapsiblenavigationcalltoaction",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Select the specific page where this CTA should not appear",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "call_to_action")},
            },
        ),
        migrations.CreateModel(
            name="EmbeddedFooterCTAExcludedPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "include_children",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the CTA will also be excluded from all child pages of the selected page",
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_pages",
                        to="personalisation.embeddedfootercalltoaction",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Select the specific page where this CTA should not appear",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "call_to_action")},
            },
        ),
        migrations.CreateModel(
            name="EventCountdownCTAExcludedPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "include_children",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the CTA will also be excluded from all child pages of the selected page",
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_pages",
                        to="personalisation.eventcountdowncalltoaction",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Select the specific page where this CTA should not appear",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "call_to_action")},
            },
        ),
        migrations.CreateModel(
            name="UserActionCTAExcludedPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "include_children",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the CTA will also be excluded from all child pages of the selected page",
                    ),
                ),
                (
                    "call_to_action",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_pages",
                        to="personalisation.useractioncalltoaction",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Select the specific page where this CTA should not appear",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "call_to_action")},
            },
        ),
    ]
