# Generated by Django 3.1.10 on 2021-06-04 04:50

import datetime

import django.db.models.deletion
import wagtail.core.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_extends_image_fields"),
        ("editorial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialpage",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2021, 6, 4, 4, 50, 31, 222525, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="intro_text",
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="editorialpage", name="video", field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="video_caption",
            field=models.CharField(
                blank=True,
                help_text="The text displayed next to the video play button",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="video_preview_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
