# Generated by Django 3.1.10 on 2021-06-04 20:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0028_studentpage_student_user_image_collection"),
        ("editorial", "0003_editorial_key_detail_fields_and_panels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorialpage",
            name="intro_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="EditorialPageArea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="people.areaofexpertise",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_area",
                        to="editorial.editorialpage",
                    ),
                ),
            ],
        ),
    ]
