# Generated by Django 3.1.10 on 2021-06-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0004_editorial_area_taxonomy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorialpage", name="date", field=models.DateTimeField(),
        ),
    ]
