# Generated by Django 3.1.10 on 2021-07-16 13:57

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0005_taxonomy_additions"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialpage",
            name="quote_carousel",
            field=wagtail.fields.StreamField(
                [
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title",
                                        help_text="Enter quote text only, there is no need to add quotation marks",
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "job_title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Quote Carousel",
            ),
        ),
    ]
