# Generated by Django 3.1.10 on 2021-07-23 09:29

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0008_add_accordion_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialpage",
            name="gallery",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "slide",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "author",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                ("link", wagtail.core.blocks.URLBlock(required=False)),
                                (
                                    "course",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Gallery",
            ),
        ),
    ]
