# Generated by Django 3.1.10 on 2021-07-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0008_add_quote_block_to_body"),
        ("editorial", "0013_make_type_orderable"),
    ]

    operations = []
