# Generated by Django 3.1.10 on 2021-07-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0015_switch_intro_to_rich_text"),
        ("editorial", "0014_merge_20210723_1408"),
    ]

    operations = []
