# Generated by Django 3.1.10 on 2021-07-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0017_editorialpagerelatedprogramme"),
        ("editorial", "0016_merge_20210727_1009"),
    ]

    operations = []
