# Generated by Django 3.1.10 on 2021-07-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0018_merge_20210727_1105"),
        ("editorial", "0018_add_help_text"),
    ]

    operations = []
