# Generated by Django 3.1.10 on 2021-07-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0018_add_help_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EditorialPageSubjectPlacement",
        ),
    ]
