# Generated by Django 3.1.10 on 2021-07-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0019_merge_20210728_1147"),
        ("editorial", "0019_delete_editorialpagesubjectplacement"),
    ]

    operations = []
