# Generated by Django 3.2.11 on 2022-02-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0020_alter_editorialpage_body"),
        ("editorial", "0020_merge_20210730_1018"),
    ]

    operations = []
