# Generated by Django 3.2.11 on 2022-05-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0021_alter_editorialpage_gallery'),
        ('editorial', '0021_merge_20220202_1046'),
    ]

    operations = [
    ]
