# Generated by Django 3.2.14 on 2022-11-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0022_merge_20220524_1103"),
        ("editorial", "0022_wagtail_3_upgrade"),
    ]

    operations = []
