# Generated by Django 3.2.16 on 2023-02-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0023_editorial_page_block_image_with_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialpage',
            name='show_in_index_page',
            field=models.BooleanField(default=True, help_text='Toggle to show/hide in the index page.'),
        ),
    ]
