# Generated by Django 3.2.14 on 2022-12-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0023_editorial_page_block_image_with_caption"),
        ("editorial", "0024_alter_editorialpage_body"),
    ]

    operations = []
