# Generated by Django 3.2.16 on 2023-03-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0024_editorialpage_show_in_index_page'),
        ('editorial', '0025_merge_20221207_1212'),
    ]

    operations = [
    ]
