# Generated by Django 3.2.21 on 2023-11-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editorial", "0025_add_embed_to_richtext_in_editorialpage_more_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialpage",
            name="sticky_cta_description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="sticky_cta_link_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Link text"
            ),
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="sticky_cta_link_url",
            field=models.URLField(blank=True, verbose_name="Link URL"),
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="sticky_cta_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Page",
            ),
        ),
    ]
