# Generated by Django 3.2.16 on 2023-08-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0025_add_embed_to_richtext_in_editorialpage_more_information"),
        ("editorial", "0026_merge_20230301_0303"),
    ]

    operations = []
