# Generated by Django 4.2.11 on 2024-06-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0027_decorative_option_image_block"),
        ("editorial", "0027_required_title_and_play_button_label_gallery_block"),
    ]

    operations = []
