# Generated by Django 3.2.21 on 2023-11-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0026_add_sticky_cta_to_editorialpage"),
        ("editorial", "0027_merge_20230816_0905"),
    ]

    operations = []
