# Generated by Django 4.2.14 on 2024-08-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0028_merge_20240610_0320"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialpage",
            name="show_on_home_page",
            field=models.BooleanField(
                default=True,
                help_text="Toggle to show/hide in the listing on the home page.",
            ),
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="show_on_landing_page",
            field=models.BooleanField(
                default=True,
                help_text="Toggle to show/hide in the listing on the landing page.",
            ),
        ),
    ]
