# Generated by Django 4.2.11 on 2024-05-31 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0027_decorative_option_image_block"),
        ("editorial", "0028_merge_20231123_1442"),
    ]

    operations = []
