# Generated by Django 4.2.11 on 2024-05-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0027_required_title_and_play_button_label_gallery_block"),
        ("editorial", "0029_merge_20240531_0249"),
    ]

    operations = []
