# Generated by Django 4.2.11 on 2024-09-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0030_cta_link_block"),
        ("editorial", "0030_editorialpage_shorthand_story_id_and_more"),
    ]

    operations = []
