# Generated by Django 4.2.11 on 2024-06-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0028_merge_20240610_0320"),
        ("editorial", "0030_merge_20240531_0250"),
    ]

    operations = []
