# Generated by Django 4.2.20 on 2025-09-19 00:26

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0032_link_block_url_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorialpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("image", 0),
                    ("image_with_caption", 3),
                    ("heading", 4),
                    ("paragraph", 5),
                    ("embed", 6),
                    ("quote", 8),
                    ("livestream_video", 12),
                    ("cta_link", 16),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Toggle to make image decorative so they can be ignored by assistive technologies.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("caption", 1), ("decorative", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/heading_block.html",
                        },
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {}),
                    6: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "help_text": "Enter quote text only, there is no need to add quotation marks",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 7), ("author", 1), ("job_title", 1)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title to identify the video. Not shown on the page.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "The URL of the video to show.",
                            "label": "Video URL",
                            "max_length": 1000,
                        },
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "The poster image to show as a placeholder for the video. For best results use an image 1920x1080 pixels"
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("video_url", 10), ("poster_image", 11)]],
                        {},
                    ),
                    13: (
                        "rca.navigation.models.URLOrRelativeURLBLock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    14: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the page's own title, required if using a URL",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 13), ("page", 14), ("title", 15)]],
                        {},
                    ),
                },
            ),
        ),
    ]
