# Generated by Django 2.2.9 on 2020-04-16 07:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailforms", "0003_capitalizeverbose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("images", "0002_customimage_file_hash"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtailsearchpromotions", "0002_capitalizeverbose"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="SchoolsAndResearchPage", new_name="SchoolPage")
    ]
