# Generated by Django 2.2.12 on 2020-12-10 12:42

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0052_pagelogentry"),
        ("images", "0003_extends_image_fields"),
        ("schools", "0003_improve_relationships_between_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_colour_option",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Light text on dark image"),
                            (2, "dark text on light image"),
                        ]
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_items",
                        to="wagtailcore.Page",
                    ),
                ),
            ],
        ),
    ]
