# Generated by Django 2.2.12 on 2020-12-10 15:38

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_heroitem"),
    ]

    operations = [
        migrations.RemoveField(model_name="schoolpage", name="description",),
        migrations.AddField(
            model_name="schoolpage",
            name="introduction",
            field=wagtail.core.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
