# Generated by Django 2.2.12 on 2020-12-11 13:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_extends_image_fields"),
        ("schools", "0004_adds_hero_and_intro_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpage",
            name="body",
            field=wagtail.fields.RichTextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="introduction_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="video",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="video_caption",
            field=models.CharField(
                blank=True,
                help_text="The text displayed next to the video play button",
                max_length=80,
            ),
        ),
    ]
