# Generated by Django 2.2.12 on 2020-12-11 12:41

import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0011_merge_20200622_1033"),
        ("wagtailcore", "0052_pagelogentry"),
        ("schools", "0005_add_introduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpage",
            name="get_in_touch",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="location",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="next_open_day_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="next_open_day_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="school_dean",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="people.StaffPage",
            ),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="social_links",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "Link",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                ("url", wagtail.core.blocks.URLBlock(required=False)),
                            ]
                        ),
                    )
                ],
                default="",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OpenDayLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                ("link_text", models.CharField(blank=True, max_length=255)),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_day_link",
                        to="schools.SchoolPage",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
