# Generated by Django 2.2.12 on 2021-01-10 09:38

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_extends_image_fields"),
        ("schools", "0007_adds_collaborators"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolPageStatsBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                (
                    "statistics",
                    wagtail.fields.StreamField(
                        [
                            (
                                "statistic",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "summary",
                                            wagtail.blocks.CharBlock(
                                                help_text="E.g.  1 in 3 of our graduates are business owners or independent professionals",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "before",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "after",
                                            wagtail.blocks.CharBlock(
                                                help_text="E.g. '%'",
                                                max_length=2,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "number",
                                            wagtail.blocks.IntegerBlock(
                                                help_text="E.g. '33'", required=False
                                            ),
                                        ),
                                        (
                                            "meta",
                                            wagtail.blocks.CharBlock(
                                                help_text="Small title below the number, e.g 'Nationalities'",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats_block",
                        to="schools.SchoolPage",
                    ),
                ),
            ],
        ),
    ]
