# Generated by Django 2.2.12 on 2020-12-11 15:20

import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_adds_video_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolPageTeaser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                ("summary", models.CharField(max_length=250)),
                (
                    "pages",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "Page",
                                wagtail.core.blocks.StreamBlock(
                                    [
                                        (
                                            "page",
                                            wagtail.core.blocks.PageChooserBlock(),
                                        ),
                                        (
                                            "custom_teaser",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "title",
                                                        wagtail.core.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "meta",
                                                        wagtail.core.blocks.CharBlock(
                                                            help_text="Small tag value displayed below the title",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "text",
                                                        wagtail.core.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "image",
                                                        wagtail.images.blocks.ImageChooserBlock(),
                                                    ),
                                                    (
                                                        "link",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "url",
                                                                    wagtail.core.blocks.URLBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                            ],
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ],
                                    max_num=3,
                                ),
                            )
                        ]
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_teasers",
                        to="schools.SchoolPage",
                    ),
                ),
            ],
        ),
    ]
