# Generated by Django 2.2.12 on 2021-01-15 11:49

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models

import rca.navigation.models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0052_pagelogentry"),
        ("images", "0003_extends_image_fields"),
        ("schools", "0012_adds_news_events_and_stories"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpage",
            name="staff_cta_block",
            field=wagtail.fields.StreamField(
                [
                    (
                        "call_to_action",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="A large heading diplayed at the top of block",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="An optional link to display below the expanded content",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="text promo",
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="staff_external_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    rca.navigation.models.URLOrRelativeURLBLock(
                                        required=False
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title, required if using a URL",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Links",
            ),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="staff_external_links_heading",
            field=models.CharField(
                blank=True, max_length=125, verbose_name="Related staff links heading"
            ),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="staff_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="staff_link_text",
            field=models.CharField(
                blank=True, help_text="E.g. 'See all staff'", max_length=125
            ),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="staff_summary",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Related staff summary text"
            ),
        ),
        migrations.AddField(
            model_name="schoolpage",
            name="staff_title",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Related staff title"
            ),
        ),
        migrations.CreateModel(
            name="SchoolPagePageStaff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=125)),
                ("surname", models.CharField(blank=-1, max_length=125)),
                ("role", models.CharField(blank=True, max_length=125)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not displayed for small teaser profiles"
                    ),
                ),
                ("link", models.URLField(blank=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_staff",
                        to="schools.SchoolPage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
