# Generated by Django 2.2.12 on 2021-01-05 08:45

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0018_name_updates"),
        ("schools", "0014_add_related_short_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpage",
            name="legacy_news_and_event_tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Specify one or more tags to identify related news and events from the legacy site. A maximum of three items with the same combination of tags will then be displayed on the page.",
                through="utils.LegacySiteTaggedPage",
                to="utils.LegacySiteTag",
                verbose_name="Legacy news and events tags",
            ),
        ),
    ]
