# Generated by Django 2.2.12 on 2021-01-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0016_introduction_image_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolpageteaser",
            name="summary",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
