# Generated by Django 2.2.12 on 2021-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0016_homepagestudentstories"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpage",
            name="news_and_events_heading",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
