# Generated by Django 2.2.12 on 2021-01-20 10:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_summary_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpageteaser',
            name='pages',
            field=wagtail.core.fields.StreamField([('Page', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('custom_teaser', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('meta', wagtail.core.blocks.CharBlock(help_text='Small tag value displayed below the title', required=False)), ('text', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))], required=False))]))], max_num=6))]),
        ),
    ]
