# Generated by Django 2.2.12 on 2021-02-10 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0024_set_cta_max_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolpagerelatedshortcourse",
            name="page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
    ]
