# Generated by Django 2.2.12 on 2021-02-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0026_add_extra_links_and_cta"),
        ("schools", "0026_add_research_section_link"),
    ]

    operations = []
