# Generated by Django 2.2.19 on 2021-04-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0027_merge_20210212_1521"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="heroitem",
            name="hero_colour_option",
        ),
    ]
