# Generated by Django 3.1.10 on 2021-07-05 12:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_remove_hero_colour_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpage',
            name='programmes_cta_block',
            field=wagtail.core.fields.StreamField([('call_to_action', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A large heading diplayed at the top of block', required=False)), ('description', wagtail.core.blocks.CharBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))], help_text='An optional link to display below the expanded content', required=False))], label='text promo'))], blank=True),
        ),
        migrations.AlterField(
            model_name='schoolpage',
            name='research_cta_block',
            field=wagtail.core.fields.StreamField([('call_to_action', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A large heading diplayed at the top of block', required=False)), ('description', wagtail.core.blocks.CharBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))], help_text='An optional link to display below the expanded content', required=False))], label='text promo'))], blank=True),
        ),
        migrations.AlterField(
            model_name='schoolpage',
            name='social_links',
            field=wagtail.core.fields.StreamField([('Link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='schoolpage',
            name='staff_cta_block',
            field=wagtail.core.fields.StreamField([('call_to_action', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A large heading diplayed at the top of block', required=False)), ('description', wagtail.core.blocks.CharBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))], help_text='An optional link to display below the expanded content', required=False))], label='text promo'))], blank=True),
        ),
    ]
