# Generated by Django 3.1.10 on 2021-07-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0029_upgrade_wagtail_streamfield_changes"),
        ("schools", "0029_add_contact_fields"),
    ]

    operations = []
