# Generated by Django 3.1.10 on 2021-10-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0030_merge_20210720_0923"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpage",
            name="intranet_slug",
            field=models.SlugField(
                blank=True,
                help_text="In order to import events and news to the intranet, this             slug value should match the category of the School Category on the             intranet",
            ),
        ),
    ]
