# Generated by Django 3.1.10 on 2021-07-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_merge_20210715_1350'),
        ('schools', '0030_merge_20210720_0923'),
    ]

    operations = [
    ]
