# Generated by Django 3.1.10 on 2021-10-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0031_merge_20210720_1450"),
        ("schools", "0031_add_intranet_slug_field"),
    ]

    operations = []
