# Generated by Django 3.2.14 on 2022-11-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0032_merge_20211024_0142"),
        ("schools", "0032_wagtail_3_upgrade"),
    ]

    operations = []
