# Generated by Django 5.2.17 on 2026-08-28 08:53

from django.db import migrations

PAGE_TYPES_RELATED_SCHOOL_PAGE = [
    ("people.StaffPage", "related_schools"),
    ("people.StudentPage", "related_schools"),
    ("events.EventDetailPage", "related_schools"),
    ("editorial.EditorialPage", "related_schools"),
    ("projects.ProjectPage", "related_school_pages"),
    ("programmes.ProgrammePage", "related_schools_and_research_pages"),
    ("shortcourses.ShortCoursePage", "related_schools_and_research_pages"),
]

OLD_SCHOOL_PAGE_TITLE = "School of Communication"
NEW_SCHOOL_PAGE_TITLE = "School of Communication & Design"


def forward(apps, schema_editor):
    SchoolPage = apps.get_model("schools", "SchoolPage")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Revision = apps.get_model("wagtailcore", "Revision")

    old_school_page = SchoolPage.objects.filter(title=OLD_SCHOOL_PAGE_TITLE).first()
    new_school_page = SchoolPage.objects.filter(title=NEW_SCHOOL_PAGE_TITLE).first()

    if not old_school_page or not new_school_page:
        return

    for page_type, field_name in PAGE_TYPES_RELATED_SCHOOL_PAGE:
        page_model = apps.get_model(page_type)
        content_type = ContentType.objects.get_for_model(page_model)

        pages_with_old_school = page_model.objects.filter(
            **{f"{field_name}__page_id": old_school_page.id}
        ).distinct()

        for page in pages_with_old_school:
            related_manager = getattr(page, field_name)
            old_items = related_manager.filter(page_id=old_school_page.id)
            has_new_school = related_manager.filter(
                page_id=new_school_page.id
            ).exists()

            if has_new_school:
                # The new school is already related
                # Drop the old entries, rather than leaving a duplicate relation.
                old_items.delete()
            else:
                # Repoint one old entry to the new school, preserving
                # its position in the list, and drop any further
                # duplicates of the old school.
                first_old_item = old_items.first()
                first_old_item.page_id = new_school_page.id
                first_old_item.save(update_fields=["page"])
                old_items.exclude(pk=first_old_item.pk).delete()

        # Revisions: each revision only needs its own content, so check
        # every revision of this content type in one query rather than
        # nesting this inside the page loop above. Stream via .iterator()
        # rather than loading every revision (and its full JSON content)
        # into memory at once — this OOM'd the Heroku release dyno when
        # this migration first shipped.
        for revision in Revision.objects.filter(
            content_type_id=content_type.pk
        ).iterator(chunk_size=200):
            content = revision.content
            items = content.get(field_name)
            if not items:
                continue

            old_indexes = [
                i for i, item in enumerate(items) if item.get("page") == old_school_page.id
            ]

            if not old_indexes:
                continue

            has_new_school = any(
                item.get("page") == new_school_page.id for item in items
            )

            if has_new_school:
                # The new school is already related
                # Drop the old entries, rather than leaving a duplicate relation.
                content[field_name] = [
                    item for i, item in enumerate(items) if i not in old_indexes
                ]
            else:
                # Repoint one old entry to the new school, preserving
                # its position in the list, and drop any further
                # duplicates of the old school.
                first_old_index = old_indexes[0]
                items[first_old_index]["page"] = new_school_page.id
                content[field_name] = [
                    item
                    for i, item in enumerate(items)
                    if i == first_old_index or item.get("page") != old_school_page.id
                ]

            revision.content = content
            revision.save(update_fields=["content"])



class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0033_link_block_url_label"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("people", "0035_staffpage_research_profile_url"),
        ("events", "0025_video_stream_block"),
        ("editorial", "0033_video_stream_block"),
        ("projects", "0032_required_title_and_play_button_label_gallery_block"),
        ("programmes", "0104_programmepage_exclude_from_programme_finder"),
        ("shortcourses", "0041_remove_programme_type_field"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
