name: test

on: workflow_call

jobs:
  python-tests:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: rca.settings.test
      SECRET_KEY: testingsecretkey
      SECURE_SSL_REDIRECT: false
      ALLOWED_HOSTS: localhost
      DATABASE_URL: postgres://postgres:postgres@localhost/postgres
      BIRDBATH_REQUIRED: false

    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.8.5
      - name: Install Poetry
        run: |
          poetry config virtualenvs.create false &&
          poetry install
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install npm dependencies
        run: npm install
      - name: Compile static files
        run: npm run build:prod
      - name: collectstatic
        run: python manage.py collectstatic --verbosity 0 --noinput --clear
      - name: System checks
        run: python manage.py check
      - name: Missing migrations
        run: python manage.py makemigrations --check --noinput
      - name: Test and Coverage
        run: |
          coverage run ./manage.py test --settings=rca.settings.test
          coverage report
          coverage xml
          bash <(curl -s https://codecov.io/bash) -t $COVERAGE_TOKEN
